Repository FuelLabs/fuel-indexer, pull requests merged in 2022-06, with the labels that each got.

#61 Update out-of-date lock file following #32
  Cargo.lock
Labels: bug, ci, blocker

#31 Refactor CI into concurrent jobs. Add mdbook and udeps checks.
  .github/workflows/ci.yml
  indexer/tests/test_indexer.rs
Labels: enhancement, ci

#70 Update gh-pages workflow w/ redirect
  .github/workflows/gh-pages.yml
Labels: ci

#72 Update mdbook outline
  README.md
  docs/README.md
  docs/src/SUMMARY.md
  docs/src/examples/hello-indexer.md
  docs/src/examples/index.md
  docs/src/getting-started/application-dependencies.md
  docs/src/getting-started/index.md
  docs/src/getting-started/setup.md
  docs/src/getting-started/system-dependencies.md
  docs/src/the-fuel-indexer.md
Labels: documentation

#75 Add udeps CI check
  .github/workflows/ci.yml
  Cargo.lock
  api_server/Cargo.toml
  derive/Cargo.toml
  indexer/Cargo.toml
  schema/Cargo.toml
Labels: ci

#79 Add project structure to mdbook
  docs/src/SUMMARY.md
  docs/src/getting-started/fuel-indexer-project.md
  docs/src/getting-started/index.md
  indexer/src/README.md
  schema/README.md
Labels: documentation

#77 Add explanation for deps
  docs/src/getting-started/system-dependencies.md
Labels: documentation

#76 Add types to mdbook
  docs/src/SUMMARY.md
  docs/src/database/conventions.md
  docs/src/database/index.md
  docs/src/database/types.md
  docs/src/examples/hello-indexer.md
  docs/src/examples/index.md
  docs/src/getting-started/application-dependencies.md
  docs/src/getting-started/basics.md
Labels: documentation
