Repository FuelLabs/fuel-indexer, pull requests merged in 2022-12, with the labels that each got.

#381 update ci workflow
  .github/workflows/ci.yml
Labels: ci

#373 Allow for live index to be stopped
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer-lib/src/utils.rs
  packages/fuel-indexer-tests/assets/explorer_index.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/assets/simple_wasm.wasm
  packages/fuel-indexer-tests/tests/service.rs
  packages/fuel-indexer/src/bin/fuel-indexer.rs
  packages/fuel-indexer/src/service.rs
Labels: bug, enhancement

#384 support identity types
  Cargo.lock
  docs/src/examples/block-explorer.md
  docs/src/examples/hello-world.md
  docs/src/quickstart/index.md
  examples/block-explorer/explorer-index/src/lib.rs
  examples/block-explorer/schema/explorer_index.schema.graphql
  examples/hello-world/hello-index/src/lib.rs
  examples/hello-world/schema/hello_index.schema.graphql
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-plugin/src/lib.rs
  packages/fuel-indexer-schema/src/base.graphql
  packages/fuel-indexer-schema/src/explorer.graphql
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-schema/src/snapshots/fuel_indexer_schema__tests__fragments-15.snap
  packages/fuel-indexer-schema/src/snapshots/fuel_indexer_schema__tests__fragments-16.snap
  packages/fuel-indexer-schema/src/snapshots/fuel_indexer_schema__tests__fragments-17.snap
  packages/fuel-indexer-schema/src/utils.rs
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/assets/explorer_index.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/assets/simple_wasm.wasm
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/Forc.lock
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test-abi.json
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test.bin
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/src/main.sw
  packages/fuel-indexer-tests/tests/e2e.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.stderr
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.stderr
  packages/fuel-indexer-types/Cargo.toml
  packages/fuel-indexer-types/src/abi.rs
  packages/fuel-indexer-types/src/lib.rs
  packages/fuel-indexer-types/src/tx.rs
Labels: enhancement

#388 v0.1.9
  Cargo.lock
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-database/Cargo.toml
  packages/fuel-indexer-database/database-types/Cargo.toml
  packages/fuel-indexer-database/postgres/Cargo.toml
  packages/fuel-indexer-database/sqlite/Cargo.toml
  packages/fuel-indexer-lib/Cargo.toml
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-metrics/Cargo.toml
  packages/fuel-indexer-plugin/Cargo.toml
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-types/Cargo.toml
  packages/fuel-indexer/Cargo.toml
  plugins/forc-index/Cargo.toml
Labels: release

#387 Add feature `start_block` and fix `next_cursor` logic
  packages/fuel-indexer/src/service.rs
Labels: enhancement

#392 update explorer example
  docs/src/examples/block-explorer.md
Labels: documentation, book

#395 update release ci
  .github/workflows/ci.yml
Labels: ci

#397 Add version
  packages/fuel-indexer-lib/src/config.rs
Labels: bug

#402 add indexer srvc fixture
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/src/lib.rs
  packages/fuel-indexer-tests/tests/e2e.rs
  packages/fuel-indexer-tests/tests/service.rs
  packages/fuel-indexer/src/service.rs
Labels: testing, code quality

#403 Fix pool usage across the indexer
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-api-server/src/bin/fuel-indexer-api-server.rs
  packages/fuel-indexer-database/src/lib.rs
  packages/fuel-indexer-schema/src/db/manager.rs
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/database.rs
  packages/fuel-indexer/src/bin/fuel-indexer.rs
  packages/fuel-indexer/src/service.rs
Labels: bug, code quality

#406 Add multiarg + callreturn tests
  Cargo.lock
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-schema/src/base.graphql
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/assets/explorer_index.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/assets/simple_wasm.wasm
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/components/web/src/bin/web-api.rs
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/Forc.lock
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test-abi.json
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test.bin
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/src/main.sw
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/e2e.rs
  packages/fuel-indexer-tests/tests/lib.rs
  packages/fuel-indexer-tests/tests/metrics.rs
  packages/fuel-indexer-types/src/lib.rs
  packages/fuel-indexer/src/service.rs
Labels: testing

#405 Allow for optional ABI JSON tokens in #[indexer] codegen
  examples/block-explorer/manifest.yaml
  packages/fuel-indexer-macros/src/default-abi.json
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-tests/assets/explorer_index.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/assets/simple_wasm.wasm
  packages/fuel-indexer-types/src/abi.rs
  packages/fuel-indexer/src/executor.rs
Labels: bug

#407 revisit sqlx row conversion
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-database/sqlite/src/lib.rs
Labels: code quality

#411 Remove simple-wasm example
  Cargo.lock
  Cargo.toml
  examples/simple-wasm/README.md
  examples/simple-wasm/simple/Cargo.toml
  examples/simple-wasm/simple/src/main.rs
  examples/simple-wasm/simple/wallet.json
Labels: code quality

#416 bugfix: fix sqlite + cleanup
  examples/block-explorer/explorer_index.manifest.yaml
  examples/block-explorer/manifest.yaml
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-database/sqlite/src/lib.rs
  packages/fuel-indexer-database/src/lib.rs
  packages/fuel-indexer-database/src/queries.rs
  packages/fuel-indexer-lib/src/config.rs
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer-schema/src/db/manager.rs
  packages/fuel-indexer-tests/assets/explorer_index.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/assets/simple_wasm.wasm
  packages/fuel-indexer-tests/tests/metrics.rs
  packages/fuel-indexer/src/bin/fuel-indexer.rs
  packages/fuel-indexer/src/service.rs
Labels: bug, code quality

#412 forc index check
  docs/README.md
  plugins/forc-index/src/cli.rs
  plugins/forc-index/src/commands/check.rs
  plugins/forc-index/src/commands/mod.rs
  plugins/forc-index/src/ops/forc_index_check.rs
  plugins/forc-index/src/ops/forc_index_start.rs
  plugins/forc-index/src/ops/mod.rs
  plugins/forc-index/src/utils/defaults.rs
Labels: enhancement, plugin

#417 v0.1.11
  Cargo.lock
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-database/Cargo.toml
  packages/fuel-indexer-database/database-types/Cargo.toml
  packages/fuel-indexer-database/postgres/Cargo.toml
  packages/fuel-indexer-database/sqlite/Cargo.toml
  packages/fuel-indexer-lib/Cargo.toml
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-metrics/Cargo.toml
  packages/fuel-indexer-plugin/Cargo.toml
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-types/Cargo.toml
  packages/fuel-indexer/Cargo.toml
  plugins/forc-index/Cargo.toml
Labels: release

#409 update docs
  docs/src/SUMMARY.md
  docs/src/components/assets/index.md
  docs/src/components/assets/module.md
  docs/src/components/database/types.md
  docs/src/getting-started/application-dependencies.md
  docs/src/getting-started/application-dependencies/fuelup.md
  docs/src/getting-started/application-dependencies/index.md
  docs/src/getting-started/application-dependencies/sqlx.md
  docs/src/getting-started/application-dependencies/wasm-snip.md
  docs/src/getting-started/fuel-indexer-project.md
  docs/src/getting-started/index.md
  docs/src/getting-started/installing-rust.md
  docs/src/getting-started/system-dependencies.md
  docs/src/plugins/forc-index.md
  plugins/forc-index/README.md
Labels: documentation, book

#418 docs: Update README
  docs/README.md
Labels: documentation

#422 chore: cleanup config
  Cargo.lock
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-lib/Cargo.toml
  packages/fuel-indexer-lib/src/config/database.rs
  packages/fuel-indexer-lib/src/config/fuel_node.rs
  packages/fuel-indexer-lib/src/config/graphql.rs
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-lib/src/utils.rs
  packages/fuel-indexer-tests/assets/explorer_index.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/assets/simple_wasm.wasm
Labels: code quality

#419 enhancement: add docker test env
  Cargo.lock
  docs/src/quickstart/index.md
  examples/block-explorer/explorer-index/src/lib.rs
  examples/hello-world/hello-index/src/lib.rs
  packages/fuel-indexer-lib/Cargo.toml
  packages/fuel-indexer-lib/src/utils.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-plugin/src/lib.rs
  packages/fuel-indexer-schema/src/db/tables.rs
  packages/fuel-indexer-tests/assets/explorer_index.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/assets/simple_wasm.wasm
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.stderr
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.stderr
  packages/fuel-indexer-types/Cargo.toml
  packages/fuel-indexer-types/src/abi.rs
  packages/fuel-indexer-types/src/lib.rs
  packages/fuel-indexer-types/src/tx.rs
  plugins/forc-index/src/ops/forc_index_check.rs
  plugins/forc-index/src/ops/forc_index_init.rs
  plugins/forc-index/src/utils/defaults.rs
  scripts/docker-compose.yaml
Labels: documentation, enhancement, code quality

#427 fix (fuel-indexer): Make sure that handle for old executor is aborted on redeploy
  packages/fuel-indexer/src/service.rs
Labels: bug

#425 feat: add native execution
  Cargo.lock
  Cargo.toml
  docs/src/examples/block-explorer.md
  examples/hello-world-native/hello-index-native/Cargo.toml
  examples/hello-world-native/hello-index-native/src/main.rs
  examples/hello-world-native/hello_index_native.manifest.yaml
  examples/hello-world-native/schema/hello_index_native.schema.graphql
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-api-server/src/bin/fuel-indexer-api-server.rs
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-database/sqlite/src/lib.rs
  packages/fuel-indexer-database/src/queries.rs
  packages/fuel-indexer-lib/src/manifest.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-macros/src/native.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-macros/src/wasm.rs
  packages/fuel-indexer-metrics/src/queries/postgres.rs
  packages/fuel-indexer-metrics/src/queries/sqlite.rs
  packages/fuel-indexer-plugin/Cargo.toml
  packages/fuel-indexer-plugin/src/lib.rs
  packages/fuel-indexer-plugin/src/native.rs
  packages/fuel-indexer-plugin/src/wasm.rs
  packages/fuel-indexer-schema/src/db/tables.rs
  packages/fuel-indexer-tests/assets/explorer_index.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.yaml
  packages/fuel-indexer-tests/assets/simple_wasm.wasm
  packages/fuel-indexer-tests/tests/database.rs
  packages/fuel-indexer-tests/tests/metrics.rs
  packages/fuel-indexer-types/src/lib.rs
  packages/fuel-indexer/src/bin/fuel-indexer.rs
  packages/fuel-indexer/src/database.rs
  packages/fuel-indexer/src/executor.rs
  packages/fuel-indexer/src/ffi.rs
  packages/fuel-indexer/src/lib.rs
  packages/fuel-indexer/src/service.rs
  plugins/forc-index/src/commands/init.rs
  plugins/forc-index/src/commands/new.rs
  plugins/forc-index/src/ops/forc_index_init.rs
  plugins/forc-index/src/ops/forc_index_new.rs
  plugins/forc-index/src/utils/defaults.rs
Labels: enhancement

#431 chore: break out tests by db
  .github/workflows/ci.yml
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/scripts/e2e.bash
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_sqlite.rs
  packages/fuel-indexer-tests/tests/e2e/metrics_postgres.rs
  packages/fuel-indexer-tests/tests/e2e/metrics_sqlite.rs
  packages/fuel-indexer-tests/tests/e2e/mod.rs
  packages/fuel-indexer-tests/tests/integration/database.rs
  packages/fuel-indexer-tests/tests/integration/graphql.rs
  packages/fuel-indexer-tests/tests/integration/mod.rs
  packages/fuel-indexer-tests/tests/integration/service.rs
  packages/fuel-indexer-tests/tests/lib.rs
  packages/fuel-indexer-tests/tests/metrics.rs
  plugins/forc-index/src/ops/forc_index_init.rs
Labels: testing, code quality

#430 fix (fuel-indexer,fuel-indexer-types): Re-integrate block producer
  Cargo.lock
  docs/src/indexing/blocks-and-transactions.md
  examples/block-explorer/explorer-index/src/lib.rs
  examples/block-explorer/schema/explorer_index.schema.graphql
  examples/hello-world/hello-bin/Cargo.toml
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/assets/explorer_index.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/assets/simple_wasm.wasm
  packages/fuel-indexer-tests/components/web/Cargo.toml
  packages/fuel-indexer-tests/components/web/src/bin/web-api.rs
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/integration/service.rs
  packages/fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_multi_type.rs
  packages/fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_single_type.rs
  packages/fuel-indexer-types/src/abi.rs
  packages/fuel-indexer/Cargo.toml
  packages/fuel-indexer/src/service.rs
Labels: enhancement

#433 chore: add web test fixture
  Cargo.lock
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/components/web/src/bin/web-api.rs
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/src/lib.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_sqlite.rs
Labels: testing, code quality

#434 chore: remove simple wasm example
  Cargo.toml
  examples/simple-wasm/manifest.yaml
  examples/simple-wasm/simple-wasm/Cargo.toml
  packages/fuel-indexer-tests/assets/explorer_index.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/assets/simple_wasm.wasm
  packages/fuel-indexer-tests/components/indices/simple-wasm/contracts/simple-wasm/.gitignore
  packages/fuel-indexer-tests/components/indices/simple-wasm/contracts/simple-wasm/Forc.lock
  packages/fuel-indexer-tests/components/indices/simple-wasm/contracts/simple-wasm/Forc.toml
  packages/fuel-indexer-tests/components/indices/simple-wasm/contracts/simple-wasm/out/debug/contracts-abi.json
  packages/fuel-indexer-tests/components/indices/simple-wasm/contracts/simple-wasm/out/debug/contracts-flat-abi.json
  packages/fuel-indexer-tests/components/indices/simple-wasm/contracts/simple-wasm/out/debug/contracts-storage_slots.json
  packages/fuel-indexer-tests/components/indices/simple-wasm/contracts/simple-wasm/out/debug/contracts.bin
  packages/fuel-indexer-tests/components/indices/simple-wasm/contracts/simple-wasm/src/main.sw
  packages/fuel-indexer-tests/components/indices/simple-wasm/manifest.yaml
  packages/fuel-indexer-tests/components/indices/simple-wasm/schema/schema.graphql
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple-wasm/.cargo/config
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple-wasm/Cargo.toml
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple-wasm/src/lib.rs
Labels: code quality

#439 v0.1.12
  Cargo.lock
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-database/Cargo.toml
  packages/fuel-indexer-database/database-types/Cargo.toml
  packages/fuel-indexer-database/postgres/Cargo.toml
  packages/fuel-indexer-database/sqlite/Cargo.toml
  packages/fuel-indexer-lib/Cargo.toml
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-metrics/Cargo.toml
  packages/fuel-indexer-plugin/Cargo.toml
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-types/Cargo.toml
  packages/fuel-indexer/Cargo.toml
  plugins/forc-index/Cargo.toml
Labels: release

#437 enhancement (fuel-indexer-tests): Add axum fixture for metrics tests
  .github/workflows/ci.yml
  Cargo.lock
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-api-server/src/bin/fuel-indexer-api-server.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/e2e/metrics_sqlite.rs
  packages/fuel-indexer-tests/tests/e2e/mod.rs
  packages/fuel-indexer-tests/tests/integration/mod.rs
  packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs
  packages/fuel-indexer-tests/tests/integration/web_api_sqlite.rs
  packages/fuel-indexer/src/bin/fuel-indexer.rs
Labels: testing

#436 enhancement: forc index build
  Cargo.lock
  packages/fuel-indexer-lib/src/manifest.rs
  packages/fuel-indexer/src/service.rs
  plugins/forc-index/Cargo.toml
  plugins/forc-index/src/cli.rs
  plugins/forc-index/src/commands/build.rs
  plugins/forc-index/src/commands/check.rs
  plugins/forc-index/src/commands/deploy.rs
  plugins/forc-index/src/commands/mod.rs
  plugins/forc-index/src/commands/stop.rs
  plugins/forc-index/src/ops/forc_index_build.rs
  plugins/forc-index/src/ops/forc_index_deploy.rs
  plugins/forc-index/src/ops/forc_index_init.rs
  plugins/forc-index/src/ops/mod.rs
  plugins/forc-index/src/utils/defaults.rs
Labels: enhancement, plugin

#444 refactor (forc-index): Change `forc index stop` to `forc index remove`
  docs/README.md
  docs/src/plugins/forc-index.md
  plugins/forc-index/src/cli.rs
  plugins/forc-index/src/commands/mod.rs
  plugins/forc-index/src/commands/remove.rs
  plugins/forc-index/src/ops/forc_index_remove.rs
  plugins/forc-index/src/ops/mod.rs
Labels: code quality

#442 chore: remove test web components
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  packages/fuel-indexer-tests/assets/explorer_index.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/assets/simple_wasm.wasm
  packages/fuel-indexer-tests/components/fuel-node/Cargo.toml
  packages/fuel-indexer-tests/components/fuel-node/src/main.rs
  packages/fuel-indexer-tests/components/web-api/Cargo.toml
  packages/fuel-indexer-tests/components/web-api/src/main.rs
  packages/fuel-indexer-tests/components/web/Cargo.toml
  packages/fuel-indexer-tests/components/web/README.md
  packages/fuel-indexer-tests/components/web/src/.gitkeep
  packages/fuel-indexer-tests/components/web/wallet.json
  packages/fuel-indexer-tests/scripts/e2e.bash
  scripts/utils/kill_test_components.bash
  scripts/utils/start_test_components.bash
Labels: ci, testing, code quality

#438 docs: Finalize book for holiday milestone
  docs/README.md
  docs/src/SUMMARY.md
  docs/src/components/fuel-node.md
  docs/src/components/index.md
  docs/src/getting-started/application-dependencies/database.md
  docs/src/getting-started/application-dependencies/fuelup.md
  docs/src/getting-started/application-dependencies/index.md
  docs/src/getting-started/configuration.md
  docs/src/getting-started/fuel-indexer-project.md
  docs/src/getting-started/index.md
  docs/src/img/fuel_indexer_flow.svg
  docs/src/indexing/blocks-and-transactions.md
  docs/src/indexing/index.md
  docs/src/plugins/forc-index.md
  docs/src/quickstart/index.md
Labels: documentation
