Repository FuelLabs/fuel-indexer, pull requests merged in 2022-10, with the labels that each got.

#249 Add CI job for wasm example
  .github/workflows/ci.yml
Labels: ci

#258 No restart on asset upload
  fuel-indexer-api-server/src/main.rs
  fuel-indexer-database/postgres/src/lib.rs
  fuel-indexer-database/sqlite/src/lib.rs
  fuel-indexer-database/src/queries.rs
  fuel-indexer-lib/src/lib.rs
  fuel-indexer-tests/tests/service.rs
  fuel-indexer/Cargo.toml
  fuel-indexer/src/api.rs
  fuel-indexer/src/bin/fuel-indexer.rs
  fuel-indexer/src/config.rs
  fuel-indexer/src/service.rs
Labels: enhancement

#257 Move GraphQL API component to fuel-indexer-api-server
  .github/workflows/ci.yml
  Cargo.lock
  fuel-indexer-api-server/Cargo.toml
  fuel-indexer-api-server/src/api.rs
  fuel-indexer-api-server/src/lib.rs
  fuel-indexer-api-server/src/main.rs
  fuel-indexer-lib/Cargo.toml
  fuel-indexer-lib/src/config.rs
  fuel-indexer-lib/src/lib.rs
  fuel-indexer-lib/src/manifest.rs
  fuel-indexer-lib/src/utils.rs
  fuel-indexer-schema/src/db/tables.rs
  fuel-indexer-tests/Cargo.toml
  fuel-indexer-tests/tests/database.rs
  fuel-indexer-tests/tests/executor.rs
  fuel-indexer-tests/tests/service.rs
  fuel-indexer/Cargo.toml
  fuel-indexer/src/bin/fuel-indexer.rs
  fuel-indexer/src/database.rs
  fuel-indexer/src/executor.rs
  fuel-indexer/src/lib.rs
  fuel-indexer/src/service.rs
Labels: code quality, work in progress

#259 Update mdbook
  README.md
  config.yaml
  docs/README.md
  docs/src/SUMMARY.md
  docs/src/components/assets/index.md
  docs/src/components/assets/manifest.md
  docs/src/components/assets/schema.md
  docs/src/components/assets/wasm.md
  docs/src/components/database/conventions.md
  docs/src/components/database/directives.md
  docs/src/components/database/foreign-keys.md
  docs/src/components/database/index.md
  docs/src/components/database/types.md
  docs/src/components/gql-server.md
  docs/src/components/index.md
  docs/src/components/indices/index.md
  docs/src/components/indices/registration.md
  docs/src/components/manifest.md
  docs/src/components/schema.md
  docs/src/getting-started/application-dependencies.md
  docs/src/getting-started/configuration.md
  docs/src/getting-started/fuel-indexer-project.md
  docs/src/getting-started/setup.md
  docs/src/getting-started/system-dependencies.md
  docs/src/the-fuel-indexer.md
  fuel-indexer-lib/Cargo.toml
  fuel-indexer-lib/src/config.rs
  fuel-indexer-tests/components/web/README.md
  fuel-indexer-tests/tests/e2e.rs
Labels: documentation, book

#266 Add additional receipts
  .github/workflows/ci.yml
  Cargo.lock
  fuel-indexer-api-server/Cargo.toml
  fuel-indexer-database/database-types/src/lib.rs
  fuel-indexer-database/postgres/src/lib.rs
  fuel-indexer-database/sqlite/src/lib.rs
  fuel-indexer-macros/Cargo.toml
  fuel-indexer-macros/src/indexer.rs
  fuel-indexer-macros/src/lib.rs
  fuel-indexer-macros/src/schema.rs
  fuel-indexer-plugin/src/lib.rs
  fuel-indexer-schema/src/db/tables.rs
  fuel-indexer-schema/src/lib.rs
  fuel-indexer-tests/Cargo.toml
  fuel-indexer-tests/assets/fuel_indexer_test.graphql
  fuel-indexer-tests/assets/fuel_indexer_test.wasm
  fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  fuel-indexer-tests/components/web/Cargo.toml
  fuel-indexer-tests/components/web/src/bin/web-api.rs
  fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test-abi.json
  fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test.bin
  fuel-indexer-tests/contracts/fuel-indexer-test/src/main.sw
  fuel-indexer-tests/macro-data/fail_if_attribute_abi_arg_includes_invalid_type.stderr
  fuel-indexer-tests/macro-data/fail_if_attribute_schema_arg_is_invalid.stderr
  fuel-indexer-tests/macro-data/fail_if_indexer_module_is_empty.stderr
  fuel-indexer-tests/src/lib.rs
  fuel-indexer-tests/tests/e2e.rs
  fuel-indexer-tests/tests/executor.rs
  fuel-indexer/Cargo.toml
  fuel-indexer/src/database.rs
  fuel-indexer/src/executor.rs
  fuel-indexer/src/ffi.rs
  fuel-indexer/src/lib.rs
  fuel-indexer/src/service.rs
  scripts/build_test_wasm_module.bash
  scripts/start_test_components.bash
Labels: enhancement, ci

#273 Swap manual trait impl for strum
  Cargo.lock
  docs/src/components/assets/manifest.md
  fuel-indexer-database/database-types/Cargo.toml
  fuel-indexer-database/database-types/src/lib.rs
  fuel-indexer-database/postgres/src/lib.rs
  fuel-indexer-database/sqlite/src/lib.rs
  fuel-indexer-lib/src/lib.rs
  fuel-indexer-schema/Cargo.toml
  fuel-indexer-schema/src/db/models.rs
  fuel-indexer/Cargo.toml
  fuel-indexer/src/api.rs
  fuel-indexer/src/bin/fuel-indexer.rs
  fuel-indexer/src/config.rs
  scripts/utils/README.md
Labels: code quality

#275 Readd scriptresult test
  Cargo.lock
  fuel-indexer-tests/Cargo.toml
  fuel-indexer-tests/assets/fuel_indexer_test.wasm
  fuel-indexer-tests/tests/e2e.rs
Labels: testing

#277 Add `Receipt::LogData`
  Cargo.lock
  examples/simple-wasm/simple-wasm/Cargo.toml
  examples/simple-wasm/simple/Cargo.toml
  examples/simple-wasm/simple/src/main.rs
  fuel-indexer-macros/Cargo.toml
  fuel-indexer-macros/src/indexer.rs
  fuel-indexer-schema/Cargo.toml
  fuel-indexer-tests/Cargo.toml
  fuel-indexer-tests/assets/fuel_indexer_test.wasm
  fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml
  fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  fuel-indexer-tests/components/web/Cargo.toml
  fuel-indexer-tests/components/web/src/bin/fuel-node.rs
  fuel-indexer-tests/components/web/src/bin/web-api.rs
  fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test-abi.json
  fuel-indexer-tests/macro-data/fail_if_attribute_abi_arg_includes_invalid_type.rs
  fuel-indexer-tests/macro-data/fail_if_attribute_schema_arg_is_invalid.rs
  fuel-indexer-tests/macro-data/pass_if_indexer_is_valid_multi_type.rs
  fuel-indexer-tests/macro-data/pass_if_indexer_is_valid_single_type.rs
  fuel-indexer-tests/src/lib.rs
  fuel-indexer-tests/tests/e2e.rs
  fuel-indexer-tests/tests/executor.rs
  fuel-indexer-tests/tests/service.rs
  scripts/utils/start_test_components.bash
Labels: enhancement

#276 Add tests for transfer receipt type
  fuel-indexer-tests/assets/fuel_indexer_test.wasm
  fuel-indexer-tests/components/web/src/bin/web-api.rs
  fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test-abi.json
  fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test.bin
  fuel-indexer-tests/contracts/fuel-indexer-test/src/main.sw
  fuel-indexer-tests/src/lib.rs
  fuel-indexer-tests/tests/e2e.rs
Labels: testing

#282 Update sway to v0.27.0
  examples/simple-wasm/contracts/simple-wasm/Forc.lock
  examples/simple-wasm/contracts/simple-wasm/out/debug/contracts.bin
  fuel-indexer-tests/assets/fuel_indexer_test.wasm
  fuel-indexer-tests/contracts/fuel-indexer-test/Forc.lock
  fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test-abi.json
  fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test.bin
  fuel-indexer-tests/contracts/simple-wasm/Forc.lock
  fuel-indexer-tests/contracts/simple-wasm/out/debug/contracts.bin
Labels: dependencies

#281 Archive release assets + cargo verifications
  .github/workflows/ci.yml
  ci/Dockerfile.x86_64-unknown-linux-gnu-clang
Labels: ci

#279 Add basic usage example
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  docs/src/SUMMARY.md
  docs/src/components/database/directives.md
  docs/src/components/database/foreign-keys.md
  docs/src/examples/block-explorer.md
  docs/src/examples/hello-indexer.md
  docs/src/examples/index.md
  examples/block-explorer/README.md
  examples/block-explorer/contracts/.gitkeep
  examples/block-explorer/explorer-index/.cargo/config
  examples/block-explorer/explorer-index/Cargo.toml
  examples/block-explorer/explorer-index/src/lib.rs
  examples/block-explorer/go.bash
  examples/block-explorer/manifest.yaml
  examples/block-explorer/schema/explorer.graphql
  fuel-indexer-database/database-types/src/lib.rs
  fuel-indexer-lib/Cargo.toml
  fuel-indexer-lib/src/defaults.rs
  fuel-indexer-lib/src/lib.rs
  fuel-indexer-lib/src/manifest.rs
  fuel-indexer-lib/src/utils.rs
  fuel-indexer-macros/src/default-abi.json
  fuel-indexer-macros/src/indexer.rs
  fuel-indexer-macros/src/lib.rs
  fuel-indexer-macros/src/native.rs
  fuel-indexer-macros/src/schema.rs
  fuel-indexer-macros/src/wasm.rs
  fuel-indexer-plugin/Cargo.toml
  fuel-indexer-plugin/src/lib.rs
  fuel-indexer-schema/Cargo.toml
  fuel-indexer-schema/src/base.graphql
  fuel-indexer-schema/src/db/models.rs
  fuel-indexer-schema/src/db/tables.rs
  fuel-indexer-schema/src/directives.rs
  fuel-indexer-schema/src/lib.rs
  fuel-indexer-schema/src/types/fuel.rs
  fuel-indexer-schema/src/types/mod.rs
  fuel-indexer-schema/src/types/transaction.rs
  fuel-indexer-schema/src/utils.rs
  fuel-indexer-tests/assets/explorer_index.wasm
  fuel-indexer-tests/assets/fuel_indexer_test.wasm
  fuel-indexer-tests/assets/simple_wasm.wasm
  fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  fuel-indexer-tests/macro-data/fail_if_attribute_abi_arg_includes_invalid_type.rs
  fuel-indexer-tests/macro-data/fail_if_attribute_abi_arg_includes_invalid_type.stderr
  fuel-indexer-tests/macro-data/fail_if_attribute_schema_arg_is_invalid.rs
  fuel-indexer-tests/macro-data/fail_if_attribute_schema_arg_is_invalid.stderr
  fuel-indexer-tests/macro-data/pass_if_indexer_is_valid_multi_type.rs
  fuel-indexer-tests/macro-data/pass_if_indexer_is_valid_single_type.rs
  fuel-indexer-tests/tests/database.rs
  fuel-indexer-tests/tests/executor.rs
  fuel-indexer/src/database.rs
  fuel-indexer/src/executor.rs
  fuel-indexer/src/ffi.rs
  fuel-indexer/src/lib.rs
  fuel-indexer/src/service.rs
  scripts/utils/build_test_wasm_module.bash
  scripts/utils/start_test_components.bash
Labels: documentation, enhancement, book

#287 Add "Receipts" section to book
  README.md
  docs/CONTRIBUTING.md
  docs/src/SUMMARY.md
  docs/src/components/assets/manifest.md
  docs/src/components/assets/wasm.md
  docs/src/components/database/conventions.md
  docs/src/components/database/foreign-keys.md
  docs/src/components/database/index.md
  docs/src/components/database/types.md
  docs/src/components/graphql/api-server.md
  docs/src/components/graphql/directives.md
  docs/src/components/graphql/index.md
  docs/src/components/graphql/schema.md
  docs/src/components/index.md
  docs/src/components/indices/registration.md
  docs/src/components/schema/directives.md
  docs/src/examples/block-explorer.md
  docs/src/getting-started/application-dependencies.md
  docs/src/getting-started/configuration.md
  docs/src/getting-started/fuel-indexer-project.md
  docs/src/getting-started/index.md
  docs/src/getting-started/setup.md
  docs/src/getting-started/system-dependencies.md
  docs/src/img/fuel.png
  docs/src/indexing/index.md
  docs/src/indexing/receipts.md
  docs/src/quickstart/index.md
  docs/src/the-fuel-indexer.md
  examples/block-explorer/explorer-index/src/lib.rs
  fuel-indexer-tests/contracts/simple-wasm/Forc.lock
Labels: documentation, book

#302 v0.1.0
  Cargo.lock
  docs/src/quickstart/index.md
  examples/block-explorer/explorer-index/Cargo.toml
  examples/simple-wasm/simple-wasm/Cargo.toml
  fuel-indexer-api-server/Cargo.toml
  fuel-indexer-database/Cargo.toml
  fuel-indexer-database/postgres/Cargo.toml
  fuel-indexer-database/sqlite/Cargo.toml
  fuel-indexer-lib/Cargo.toml
  fuel-indexer-macros/Cargo.toml
  fuel-indexer-plugin/Cargo.toml
  fuel-indexer-schema/Cargo.toml
  fuel-indexer-tests/Cargo.toml
  fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml
  fuel-indexer-tests/components/web/Cargo.toml
  fuel-indexer/Cargo.toml
Labels: release
