Repository FuelLabs/fuel-indexer, pull requests merged in 2022-11, with the labels that each got.

#309 Change script perms
  .github/workflows/scripts/verify_tag.sh
Labels: ci

#310 Publish all crates
  .github/workflows/ci.yml
  Cargo.lock
  fuel-indexer-database/Cargo.toml
  fuel-indexer-database/database-types/Cargo.toml
  fuel-indexer-database/postgres/Cargo.toml
  fuel-indexer-database/sqlite/Cargo.toml
  fuel-indexer-schema/Cargo.toml
  fuel-indexer/Cargo.toml
Labels: ci, dependencies

#311 Add fuel-indexer-test version + make versions more specific
  .github/workflows/ci.yml
  docs/src/quickstart/index.md
  examples/block-explorer/explorer-index/Cargo.toml
  examples/simple-wasm/simple-wasm/Cargo.toml
  fuel-indexer-api-server/Cargo.toml
  fuel-indexer-database/Cargo.toml
  fuel-indexer-database/postgres/Cargo.toml
  fuel-indexer-database/sqlite/Cargo.toml
  fuel-indexer-macros/Cargo.toml
  fuel-indexer-plugin/Cargo.toml
  fuel-indexer-schema/Cargo.toml
  fuel-indexer-tests/Cargo.toml
  fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml
  fuel-indexer-tests/components/web/Cargo.toml
  fuel-indexer/Cargo.toml
Labels: ci

#305 Make fuel-indexer-api-server standalone
  Cargo.lock
  fuel-indexer-api-server/Cargo.toml
  fuel-indexer-api-server/src/api.rs
  fuel-indexer-api-server/src/bin/fuel-indexer-api-server.rs
  fuel-indexer-api-server/src/lib.rs
  fuel-indexer-api-server/src/uses.rs
  fuel-indexer-lib/Cargo.toml
  fuel-indexer-lib/src/config.rs
  fuel-indexer-lib/src/lib.rs
  fuel-indexer-schema/src/db.rs
  fuel-indexer-schema/src/db/manager.rs
  fuel-indexer-tests/Cargo.toml
  fuel-indexer-tests/tests/service.rs
  fuel-indexer/Cargo.toml
  fuel-indexer/src/bin/fuel-indexer.rs
  fuel-indexer/src/database.rs
  fuel-indexer/src/lib.rs
  fuel-indexer/src/service.rs
  fuel-indexer/src/test_data/contracts-abi.json
Labels: enhancement, code quality

#313 Add fuel-indexer-types
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  fuel-indexer-lib/src/utils.rs
  fuel-indexer-macros/Cargo.toml
  fuel-indexer-macros/src/indexer.rs
  fuel-indexer-macros/src/schema.rs
  fuel-indexer-plugin/Cargo.toml
  fuel-indexer-plugin/src/lib.rs
  fuel-indexer-schema/Cargo.toml
  fuel-indexer-schema/src/db/tables.rs
  fuel-indexer-schema/src/lib.rs
  fuel-indexer-schema/src/utils.rs
  fuel-indexer-tests/Cargo.toml
  fuel-indexer-tests/assets/explorer_index.wasm
  fuel-indexer-tests/assets/fuel_indexer_test.wasm
  fuel-indexer-tests/assets/simple_wasm.wasm
  fuel-indexer-tests/macro-data/fail_if_attribute_abi_arg_includes_invalid_type.stderr
  fuel-indexer-tests/macro-data/fail_if_attribute_schema_arg_is_invalid.stderr
  fuel-indexer-tests/tests/database.rs
  fuel-indexer-tests/tests/executor.rs
  fuel-indexer-types/Cargo.toml
  fuel-indexer-types/src/lib.rs
  fuel-indexer-types/src/log.rs
  fuel-indexer-types/src/native.rs
  fuel-indexer-types/src/tx.rs
  fuel-indexer/Cargo.toml
  fuel-indexer/src/executor.rs
  fuel-indexer/src/ffi.rs
  fuel-indexer/src/lib.rs
  fuel-indexer/src/service.rs
Labels: code quality

#315 Specify which crates are publishable
  .github/workflows/ci.yml
  examples/simple-wasm/simple/Cargo.toml
  fuel-indexer-api-server/Cargo.toml
  fuel-indexer-macros/Cargo.toml
  fuel-indexer-macros/src/indexer.rs
  fuel-indexer-plugin/Cargo.toml
  fuel-indexer-schema/Cargo.toml
  fuel-indexer-tests/components/web/Cargo.toml
  fuel-indexer-tests/components/web/src/bin/fuel-node.rs
  fuel-indexer-tests/components/web/src/bin/web-api.rs
  fuel-indexer-tests/tests/service.rs
  fuel-indexer-types/Cargo.toml
  fuel-indexer/Cargo.toml
Labels: ci

#319 v0.1.0-isolate-crates
  .github/workflows/ci.yml
  fuel-indexer-database/database-types/Cargo.toml
  fuel-indexer-lib/Cargo.toml
  fuel-indexer-types/Cargo.toml
Labels: ci

#322 v0.1.1
  .github/workflows/ci.yml
  Cargo.lock
  docs/src/quickstart/index.md
  examples/block-explorer/explorer-index/Cargo.toml
  examples/simple-wasm/simple-wasm/Cargo.toml
  fuel-indexer-api-server/Cargo.toml
  fuel-indexer-database/Cargo.toml
  fuel-indexer-database/database-types/Cargo.toml
  fuel-indexer-database/postgres/Cargo.toml
  fuel-indexer-database/sqlite/Cargo.toml
  fuel-indexer-lib/Cargo.toml
  fuel-indexer-macros/Cargo.toml
  fuel-indexer-plugin/Cargo.toml
  fuel-indexer-schema/Cargo.toml
  fuel-indexer-tests/Cargo.toml
  fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml
  fuel-indexer-tests/components/web/Cargo.toml
  fuel-indexer-types/Cargo.toml
  fuel-indexer/Cargo.toml
Labels: ci

#323 v0.1.2
  .github/workflows/ci.yml
  Cargo.lock
  fuel-indexer-api-server/Cargo.toml
  fuel-indexer-database/Cargo.toml
  fuel-indexer-database/database-types/Cargo.toml
  fuel-indexer-database/postgres/Cargo.toml
  fuel-indexer-database/sqlite/Cargo.toml
  fuel-indexer-lib/Cargo.toml
  fuel-indexer-macros/Cargo.toml
  fuel-indexer-plugin/Cargo.toml
  fuel-indexer-schema/Cargo.toml
  fuel-indexer-types/Cargo.toml
  fuel-indexer/Cargo.toml
Labels: ci

#328 Make entire config optional
  fuel-indexer-lib/src/config.rs
Labels: enhancement

#330 rustc 1.65 docker
  deployment/Dockerfile
Labels: infrastructure, dependencies

#329 Allow multi fks on tables
  fuel-indexer-schema/src/db/models.rs
  fuel-indexer-schema/src/db/tables.rs
Labels: enhancement

#324 Upgrade dependencies
  Cargo.lock
  docs/src/examples/block-explorer.md
  docs/src/quickstart/index.md
  examples/block-explorer/explorer-index/Cargo.toml
  examples/block-explorer/explorer-index/src/lib.rs
  examples/block-explorer/schema/explorer.graphql
  examples/simple-wasm/simple-wasm/Cargo.toml
  examples/simple-wasm/simple/Cargo.toml
  examples/simple-wasm/simple/src/main.rs
  fuel-indexer-api-server/Cargo.toml
  fuel-indexer-macros/Cargo.toml
  fuel-indexer-schema/Cargo.toml
  fuel-indexer-schema/src/explorer.graphql
  fuel-indexer-schema/src/utils.rs
  fuel-indexer-tests/Cargo.toml
  fuel-indexer-tests/assets/explorer_index.wasm
  fuel-indexer-tests/assets/fuel_indexer_test.graphql
  fuel-indexer-tests/assets/fuel_indexer_test.wasm
  fuel-indexer-tests/assets/simple_wasm.wasm
  fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml
  fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  fuel-indexer-tests/components/web/Cargo.toml
  fuel-indexer-tests/components/web/src/bin/fuel-node.rs
  fuel-indexer-tests/components/web/src/bin/web-api.rs
  fuel-indexer-tests/contracts/fuel-indexer-test/Forc.lock
  fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test.bin
  fuel-indexer-tests/contracts/fuel-indexer-test/src/main.sw
  fuel-indexer-tests/contracts/simple-wasm/Forc.lock
  fuel-indexer-tests/contracts/simple-wasm/src/main.sw
  fuel-indexer-tests/tests/e2e.rs
  fuel-indexer-tests/tests/executor.rs
  fuel-indexer-tests/tests/service.rs
  fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.rs
  fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.stderr
  fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.rs
  fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.stderr
  fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_multi_type.rs
  fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_single_type.rs
  fuel-indexer-types/Cargo.toml
  fuel-indexer-types/src/abi.rs
  fuel-indexer-types/src/tx.rs
  fuel-indexer/Cargo.toml
  fuel-indexer/src/service.rs
Labels: dependencies

#336 Add MessageId as a GraphQL base type
  fuel-indexer-database/database-types/src/lib.rs
  fuel-indexer-schema/src/base.graphql
  fuel-indexer-schema/src/lib.rs
  fuel-indexer-schema/src/snapshots/fuel_indexer_schema__tests__fragments-14.snap
  fuel-indexer-schema/src/utils.rs
  fuel-indexer-tests/assets/explorer_index.wasm
  fuel-indexer-tests/assets/fuel_indexer_test.graphql
  fuel-indexer-tests/assets/fuel_indexer_test.wasm
  fuel-indexer-tests/assets/simple_wasm.wasm
  fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  fuel-indexer-tests/tests/e2e.rs
Labels: enhancement

#337 Fix target typo in quickstart section
  docs/src/quickstart/index.md
Labels: documentation, book

#339 Support more architectures for release binaries
  .github/workflows/ci.yml
  Cargo.lock
  ci/Dockerfile.aarch64-unknown-linux-gnu-clang
  ci/Dockerfile.x86_64-unknown-linux-gnu-clang
  ci/build-images.sh
  ci/macos-install-packages.sh
  fuel-indexer-api-server/Cargo.toml
  fuel-indexer-api-server/src/uses.rs
  fuel-indexer-tests/Cargo.toml
  fuel-indexer-tests/assets/explorer_index.wasm
  fuel-indexer-tests/assets/fuel_indexer_test.wasm
  fuel-indexer-tests/assets/simple_wasm.wasm
  fuel-indexer-types/src/tx.rs
  fuel-indexer/Cargo.toml
  fuel-indexer/src/service.rs
Labels: enhancement, infrastructure

#342 Move away from deprecated `timestamp()` function
  Cargo.lock
  fuel-indexer-api-server/Cargo.toml
  fuel-indexer-database/Cargo.toml
  fuel-indexer-database/database-types/Cargo.toml
  fuel-indexer-database/postgres/Cargo.toml
  fuel-indexer-database/sqlite/Cargo.toml
  fuel-indexer-lib/Cargo.toml
  fuel-indexer-macros/Cargo.toml
  fuel-indexer-plugin/Cargo.toml
  fuel-indexer-schema/Cargo.toml
  fuel-indexer-tests/assets/explorer_index.wasm
  fuel-indexer-tests/assets/fuel_indexer_test.wasm
  fuel-indexer-tests/assets/simple_wasm.wasm
  fuel-indexer-types/Cargo.toml
  fuel-indexer-types/src/tx.rs
  fuel-indexer/Cargo.toml
  fuel-indexer/src/service.rs
Labels: dependencies, code quality

#345 Fix row fetching in `query_graph()` path
  fuel-indexer-database/postgres/src/lib.rs
  fuel-indexer-database/sqlite/src/lib.rs
Labels: bug

#349 Update docs and block explorer example
  docs/src/SUMMARY.md
  docs/src/components/assets/wasm.md
  docs/src/components/database/types.md
  docs/src/examples/block-explorer.md
  docs/src/quickstart/index.md
  examples/block-explorer/schema/explorer.graphql
Labels: documentation

#351 Integrate prometheus
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  config.yaml
  deployment/monitoring/fuel-indexer-service-monitor.yaml
  docs/src/components/assets/manifest.md
  fuel-indexer-api-server/Cargo.toml
  fuel-indexer-api-server/src/api.rs
  fuel-indexer-api-server/src/uses.rs
  fuel-indexer-database/postgres/Cargo.toml
  fuel-indexer-database/postgres/src/lib.rs
  fuel-indexer-database/sqlite/Cargo.toml
  fuel-indexer-database/sqlite/src/lib.rs
  fuel-indexer-database/src/queries.rs
  fuel-indexer-lib/src/config.rs
  fuel-indexer-lib/src/manifest.rs
  fuel-indexer-metrics/Cargo.toml
  fuel-indexer-metrics/src/core.rs
  fuel-indexer-metrics/src/lib.rs
  fuel-indexer-metrics/src/queries/mod.rs
  fuel-indexer-metrics/src/queries/postgres.rs
  fuel-indexer-metrics/src/queries/sqlite.rs
  fuel-indexer-tests/Cargo.toml
  fuel-indexer-tests/assets/explorer_index.wasm
  fuel-indexer-tests/assets/fuel_indexer_test.wasm
  fuel-indexer-tests/assets/fuel_indexer_test.yaml
  fuel-indexer-tests/assets/simple_wasm.wasm
  fuel-indexer-tests/components/web/src/bin/fuel-node.rs
  fuel-indexer-tests/src/fixtures.rs
  fuel-indexer-tests/src/lib.rs
  fuel-indexer-tests/tests/database.rs
  fuel-indexer-tests/tests/e2e.rs
  fuel-indexer-tests/tests/executor.rs
  fuel-indexer-tests/tests/lib.rs
  fuel-indexer-tests/tests/metrics.rs
  fuel-indexer-tests/tests/service.rs
  fuel-indexer/Cargo.toml
Labels: enhancement

#370 Update CI
  .github/workflows/ci.yml
Labels: ci

#372 Add forc-index plugin
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  plugins/.gitkeep
  plugins/forc-index/Cargo.toml
  plugins/forc-index/README.md
  plugins/forc-index/src/bin/forc-index.rs
  plugins/forc-index/src/cli.rs
  plugins/forc-index/src/commands/deploy.rs
  plugins/forc-index/src/commands/init.rs
  plugins/forc-index/src/commands/mod.rs
  plugins/forc-index/src/commands/new.rs
  plugins/forc-index/src/commands/start.rs
  plugins/forc-index/src/lib.rs
  plugins/forc-index/src/ops/forc_index_deploy.rs
  plugins/forc-index/src/ops/forc_index_init.rs
  plugins/forc-index/src/ops/forc_index_new.rs
  plugins/forc-index/src/ops/forc_index_start.rs
  plugins/forc-index/src/ops/mod.rs
  plugins/forc-index/src/utils/defaults.rs
  plugins/forc-index/src/utils/mod.rs
Labels: enhancement

#374 underscore project name
  plugins/forc-index/src/ops/forc_index_init.rs
  plugins/forc-index/src/utils/mod.rs
Labels: bug

#360 Add hello world example
  Cargo.lock
  Cargo.toml
  README.md
  docs/src/SUMMARY.md
  docs/src/examples/block-explorer.md
  docs/src/examples/hello-world.md
  docs/src/examples/index.md
  docs/src/getting-started/fuel-indexer-project.md
  docs/src/quickstart/index.md
  examples/README.md
  examples/block-explorer/explorer-index/src/lib.rs
  examples/hello-world/README.md
  examples/hello-world/contracts/greeting/.gitignore
  examples/hello-world/contracts/greeting/Forc.lock
  examples/hello-world/contracts/greeting/Forc.toml
  examples/hello-world/contracts/greeting/out/debug/greeting-abi.json
  examples/hello-world/contracts/greeting/out/debug/greeting-storage_slots.json
  examples/hello-world/contracts/greeting/out/debug/greeting.bin
  examples/hello-world/contracts/greeting/src/main.sw
  examples/hello-world/hello-bin/Cargo.toml
  examples/hello-world/hello-bin/src/main.rs
  examples/hello-world/hello-index.manifest.yaml
  examples/hello-world/hello-index/.cargo/config
  examples/hello-world/hello-index/Cargo.toml
  examples/hello-world/hello-index/src/lib.rs
  examples/hello-world/schema/hello-index.schema.graphql
  examples/simple-wasm/README.md
  examples/simple-wasm/simple/src/main.rs
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-plugin/Cargo.toml
  packages/fuel-indexer-schema/src/base.graphql
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-schema/src/snapshots/fuel_indexer_schema__tests__fragments-15.snap
  packages/fuel-indexer-schema/src/snapshots/fuel_indexer_schema__tests__fragments-16.snap
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/assets/explorer_index.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/assets/hello_index.wasm
  packages/fuel-indexer-tests/assets/simple_wasm.wasm
  packages/fuel-indexer-tests/assets/test-chain-config.json
  packages/fuel-indexer-tests/components/web/src/bin/fuel-node.rs
  packages/fuel-indexer-tests/components/web/src/bin/web-api.rs
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/src/lib.rs
  packages/fuel-indexer-tests/tests/service.rs
  packages/fuel-indexer-types/src/graphql.rs
  packages/fuel-indexer-types/src/lib.rs
  packages/fuel-indexer-types/src/tx.rs
  packages/fuel-indexer/src/service.rs
  scripts/utils/start_test_components.bash
Labels: documentation, enhancement, book
