Repository FuelLabs/fuel-indexer, pull requests merged in 2023-09, with the labels that each got.

#1342 Add Mint and Burn receipts to fuel-explorer
  examples/fuel-explorer/fuel-explorer/schema/fuel_explorer.schema.graphql
  examples/fuel-explorer/fuel-explorer/src/lib.rs
Labels: P: High

#1344 v0.20.8
  Cargo.toml
Labels: release

#1353 fix: trigger kill switch when end block is met
  packages/fuel-indexer/src/executor.rs
Labels: bug

#1358 added script and mint handling
  packages/fuel-indexer/src/executor.rs
Labels: bug

#1354 fix: support contract JSON ABI with callpaths
  packages/fuel-indexer-macros/src/helpers.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test-abi.json
Labels: bug, P: Medium

#1366 fix: bring forc index start up-to-date
  examples/fuel-explorer/fuel-explorer/src/lib.rs
  packages/fuel-indexer-benchmarks/src/bin/qa.rs
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-tests/tests/snapshots/integration_tests__commands__default_indexer_config.snap
  packages/fuel-indexer-tests/tests/snapshots/integration_tests__snapshots__default_indexer_config.snap
  packages/fuel-indexer/src/executor.rs
  plugins/forc-index/src/ops/forc_index_start.rs
Labels: bug

#1371 v0.20.10
  Cargo.lock
  Cargo.toml
Labels: release

#1376 v0.20.11
  Cargo.lock
  Cargo.toml
Labels: release

#1380 fix: update rustc specified in default indexer cargo manifest
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  ci/Dockerfile.fuel-node
  deployment/Dockerfile
  examples/fuel-explorer/fuel-explorer/Cargo.toml
  examples/hello-world-native/hello-indexer-native/Cargo.toml
  examples/hello-world/hello-indexer/Cargo.toml
  packages/fuel-indexer-lib/src/utils.rs
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/tests/config.rs
  plugins/forc-index/src/defaults.rs
  plugins/forc-index/src/ops/forc_index_build.rs
Labels: bug

#1389 v0.21.0
  Cargo.lock
  Cargo.toml
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-types/src/lib.rs
  packages/fuel-indexer-types/src/scalar.rs
  plugins/forc-index/src/defaults.rs
Labels: release
