Repository FuelLabs/fuel-indexer, pull requests merged in 2023-06, with the labels that each got.

#961 enhancement: implement more explorer types
  Cargo.lock
  examples/fuel-explorer/fuel-explorer/schema/fuel_explorer.schema.graphql
  examples/fuel-explorer/fuel-explorer/src/lib.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-plugin/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.stderr
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.stderr
  packages/fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_multi_type.rs
  packages/fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_single_type.rs
  packages/fuel-indexer-types/Cargo.toml
  packages/fuel-indexer-types/src/fuel.rs
  packages/fuel-indexer-types/src/lib.rs
  packages/fuel-indexer/Cargo.toml
  packages/fuel-indexer/src/executor.rs
Labels: enhancement, explorer

#968 chore: reduce log spam
  packages/fuel-indexer-lib/src/utils.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.stderr
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.stderr
  packages/fuel-indexer/src/commands/run.rs
  packages/fuel-indexer/src/database.rs
Labels: P: Low, chore, devx

#969 chore: optimize tx fetching
  Cargo.lock
  Cargo.toml
  packages/fuel-indexer-database/database-types/Cargo.toml
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer/Cargo.toml
  packages/fuel-indexer/assets/schema.sdl
  packages/fuel-indexer/src/executor.rs
  packages/fuel-indexer/src/lib.rs
  packages/fuel-indexer/src/queries.rs
Labels: chore

#970 v0.16.0
  Cargo.lock
  Cargo.toml
  plugins/forc-index/src/utils/defaults.rs
Labels: release

#972 fix: remove cyclic fuel-indexer-utils dep
  .github/workflows/ci.yml
  packages/fuel-indexer-macros/src/lib.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_args_include_self.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_args_not_included.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.rs
  packages/fuel-indexer-tests/trybuild/fail_if_indexer_module_is_empty.rs
  packages/fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_multi_type.rs
  packages/fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_single_type.rs
  plugins/forc-index/src/utils/defaults.rs
Labels: bug, dependencies

#974 ci: streamline crate publishing workflow
  .github/workflows/ci.yml
Labels: ci

#967 fix: update `forc index`'s `--native` indexer creation and usage
  examples/fuel-explorer/fuel-explorer/schema/fuel_explorer.schema.graphql
  packages/fuel-indexer-macros/src/native.rs
  packages/fuel-indexer-macros/src/wasm.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer/src/executor.rs
  plugins/forc-index/src/ops/forc_index_build.rs
  plugins/forc-index/src/ops/forc_index_init.rs
  plugins/forc-index/src/utils/defaults.rs
Labels: bug, plugin

#978 v0.16.1
  Cargo.lock
  Cargo.toml
Labels: release

#980 Change Manifest::FileError to include the file name
  packages/fuel-indexer-lib/src/manifest.rs
Labels: code quality

#977 chore: implement more of the explorer
  examples/fuel-explorer/fuel-explorer/schema/fuel_explorer.schema.graphql
  examples/fuel-explorer/fuel-explorer/src/lib.rs
  packages/fuel-indexer-macros/src/native.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-macros/src/wasm.rs
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-schema/src/utils.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-types/src/fuel.rs
Labels: chore, work in progress

#986 fix: various auth updates
  packages/fuel-indexer-api-server/src/models.rs
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-database/postgres/src/lib.rs
Labels: bug, P: Medium

#987 v0.16.2
  Cargo.lock
  Cargo.toml
Labels: release

#989 fix: don't panic on failed put_object
  packages/fuel-indexer/src/database.rs
Labels: bug

#992 enhancement: implement union types
  Cargo.lock
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-macros/src/helpers.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-schema/src/db/tables.rs
  packages/fuel-indexer-schema/src/parser.rs
  packages/fuel-indexer-schema/src/utils.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
Labels: enhancement, graphql, explorer

#998 chore: small default indexer updates
  plugins/forc-index/src/utils/defaults.rs
Labels: chore

#995 chore: implement union types in explorer
  docs/src/reference-guide/components/graphql/directives.md
  examples/fuel-explorer/fuel-explorer/schema/fuel_explorer.schema.graphql
  examples/fuel-explorer/fuel-explorer/src/lib.rs
  packages/fuel-indexer-database/database-types/src/directives.rs
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-graphql/src/dynamic.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-schema/src/base.graphql
  packages/fuel-indexer-schema/src/db/tables.rs
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-schema/src/parser.rs
  packages/fuel-indexer-schema/src/utils.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-types/src/scalar.rs
Labels: explorer, breaking, chore

#1004 chore: add --replace-indexer to deployment
  deployment/charts/fuel-indexer/templates/fuel-indexer-deployment.yaml
Labels: chore

#1003 enhancement: implement instantiation methods for entity types
  Cargo.lock
  examples/hello-world-native/hello-indexer-native/src/main.rs
  examples/hello-world/hello-indexer/src/lib.rs
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-macros/src/helpers.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-types/src/scalar.rs
  packages/fuel-indexer/src/database.rs
Labels: enhancement, devx, codegen

#1011 enhancement: add instantiation helpers for union types
  examples/fuel-explorer/fuel-explorer/schema/fuel_explorer.schema.graphql
  examples/fuel-explorer/fuel-explorer/src/lib.rs
  packages/fuel-indexer-macros/src/helpers.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-schema/src/parser.rs
Labels: P: Medium, devx, codegen

#1021 v0.17.0
  Cargo.lock
  Cargo.toml
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  plugins/forc-index/src/utils/defaults.rs
Labels: release

#1025 fix: update default indexer schema type
  plugins/forc-index/src/utils/defaults.rs
Labels: bug

#1016 chore: impl IDs into explorer
  examples/fuel-explorer/fuel-explorer/schema/fuel_explorer.schema.graphql
  examples/fuel-explorer/fuel-explorer/src/lib.rs
  examples/hello-world-native/hello-indexer-native/src/main.rs
  examples/hello-world/hello-indexer/src/lib.rs
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-schema/src/db/tables.rs
  packages/fuel-indexer-schema/src/parser.rs
  packages/fuel-indexer-schema/src/utils.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-utils/src/utilities.rs
  plugins/forc-index/src/utils/defaults.rs
Labels: explorer, chore, work in progress

#1007 chore: rustdoc + cleanup fuel-indexer-lib
  Cargo.toml
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-lib/README.md
  packages/fuel-indexer-lib/src/config/auth.rs
  packages/fuel-indexer-lib/src/config/cli.rs
  packages/fuel-indexer-lib/src/config/client.rs
  packages/fuel-indexer-lib/src/config/database.rs
  packages/fuel-indexer-lib/src/config/limit.rs
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer-lib/src/lib.rs
  packages/fuel-indexer-lib/src/utils.rs
  packages/fuel-indexer-plugin/src/native.rs
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer/src/lib.rs
  packages/fuel-indexer/src/service.rs
  plugins/forc-index/src/commands/auth.rs
  plugins/forc-index/src/commands/build.rs
  plugins/forc-index/src/commands/check.rs
  plugins/forc-index/src/commands/deploy.rs
  plugins/forc-index/src/commands/kill.rs
  plugins/forc-index/src/commands/remove.rs
  plugins/forc-index/src/commands/status.rs
  plugins/forc-index/src/defaults.rs
  plugins/forc-index/src/lib.rs
  plugins/forc-index/src/ops/forc_index_build.rs
  plugins/forc-index/src/ops/forc_index_check.rs
  plugins/forc-index/src/ops/forc_index_init.rs
  plugins/forc-index/src/ops/forc_index_welcome.rs
  plugins/forc-index/src/utils.rs
  plugins/forc-index/src/utils/mod.rs
Labels: documentation, code quality

#1017 feature: refactor schema and table modules
  Cargo.lock
  Cargo.toml
  examples/fuel-explorer/fuel-explorer/src/lib.rs
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-database/database-types/Cargo.toml
  packages/fuel-indexer-database/database-types/src/directives.rs
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-database/postgres/Cargo.toml
  packages/fuel-indexer-database/postgres/migrations/.gitkeep
  packages/fuel-indexer-database/postgres/migrations/20230620214812_add_graph_registry_columns_unique.down.sql
  packages/fuel-indexer-database/postgres/migrations/20230620214812_add_graph_registry_columns_unique.up.sql
  packages/fuel-indexer-database/postgres/migrations/20230621151623_update_graph_registry_columns_add_persistence.down.sql
  packages/fuel-indexer-database/postgres/migrations/20230621151623_update_graph_registry_columns_add_persistence.up.sql
  packages/fuel-indexer-database/postgres/migrations/20230621151722_update_graph_registry_type_ids_drop_virtual_cols.down.sql
  packages/fuel-indexer-database/postgres/migrations/20230621151722_update_graph_registry_type_ids_drop_virtual_cols.up.sql
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-database/src/queries.rs
  packages/fuel-indexer-graphql/Cargo.toml
  packages/fuel-indexer-graphql/src/arguments.rs
  packages/fuel-indexer-graphql/src/dynamic.rs
  packages/fuel-indexer-graphql/src/graphql.rs
  packages/fuel-indexer-graphql/src/queries.rs
  packages/fuel-indexer-lib/Cargo.toml
  packages/fuel-indexer-lib/src/graphql/base.graphql
  packages/fuel-indexer-lib/src/graphql/constants.rs
  packages/fuel-indexer-lib/src/graphql/mod.rs
  packages/fuel-indexer-lib/src/graphql/parser.rs
  packages/fuel-indexer-lib/src/graphql/types.rs
  packages/fuel-indexer-lib/src/graphql/validator.rs
  packages/fuel-indexer-lib/src/lib.rs
  packages/fuel-indexer-lib/src/manifest.rs
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-macros/src/constant.rs
  packages/fuel-indexer-macros/src/constants.rs
  packages/fuel-indexer-macros/src/decoder.rs
  packages/fuel-indexer-macros/src/helpers.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-macros/src/lib.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-schema/src/db.rs
  packages/fuel-indexer-schema/src/db/manager.rs
  packages/fuel-indexer-schema/src/db/tables.rs
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-schema/src/parser.rs
  packages/fuel-indexer-schema/src/utils.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/tests/integration/database.rs
  packages/fuel-indexer-tests/tests/integration/graphql_schema.rs
  packages/fuel-indexer-types/Cargo.toml
  packages/fuel-indexer-types/src/fuel.rs
  packages/fuel-indexer-types/src/graphql.rs
  packages/fuel-indexer-types/src/lib.rs
  packages/fuel-indexer-types/src/receipt.rs
  packages/fuel-indexer/src/database.rs
  packages/fuel-indexer/src/service.rs
Labels: code quality, big, chore, codegen

#1028 fix: downgrade `fuel-core-client` to `v0.17.2`
  Cargo.lock
  Cargo.toml
  examples/fuel-explorer/fuel-explorer/schema/fuel_explorer.schema.graphql
  examples/fuel-explorer/fuel-explorer/src/lib.rs
  examples/hello-world-native/hello-indexer-native/schema/hello_indexer_native.schema.graphql
  examples/hello-world/hello-indexer/schema/hello_indexer.schema.graphql
  examples/hello-world/hello-world-data/Cargo.toml
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-database/src/queries.rs
  packages/fuel-indexer-lib/src/graphql/mod.rs
  packages/fuel-indexer-lib/src/manifest.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/tests/integration/database.rs
  packages/fuel-indexer-tests/tests/integration/service.rs
  packages/fuel-indexer-types/src/fuel.rs
  packages/fuel-indexer-types/src/scalar.rs
  packages/fuel-indexer/Cargo.toml
  packages/fuel-indexer/src/executor.rs
  packages/fuel-indexer/src/service.rs
Labels: bug, dependencies

#1041 v0.17.2
  Cargo.lock
  Cargo.toml
Labels: release

#1044 fix: use proper type for block height
  Cargo.lock
  packages/fuel-indexer-database/postgres/Cargo.toml
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
Labels: bug
