Repository FuelLabs/fuel-indexer, pull requests merged in 2023-07, with the labels that each got.

#1052 v0.17.3
  Cargo.lock
  Cargo.toml
Labels: release

#1055 fix: forgot to update wasm lib
  plugins/forc-index/src/defaults.rs
Labels: bug

#1040 feature: support for GraphQL list types
  .github/workflows/ci.yml
  Cargo.lock
  examples/fuel-explorer/fuel-explorer/schema/fuel_explorer.schema.graphql
  examples/fuel-explorer/fuel-explorer/src/lib.rs
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-database/postgres/migrations/20230629180452_update_graph_registry_columns_add_array_coltype.down.sql
  packages/fuel-indexer-database/postgres/migrations/20230629180452_update_graph_registry_columns_add_array_coltype.up.sql
  packages/fuel-indexer-database/postgres/migrations/20230630151856_update_graph_registry_columns_extend_column_name_length.down.sql
  packages/fuel-indexer-database/postgres/migrations/20230630151856_update_graph_registry_columns_extend_column_name_length.up.sql
  packages/fuel-indexer-database/postgres/migrations/20230630152741_update_graph_registry_type_ids_extend_table_name_length.down.sql
  packages/fuel-indexer-database/postgres/migrations/20230630152741_update_graph_registry_type_ids_extend_table_name_length.up.sql
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-lib/src/graphql/mod.rs
  packages/fuel-indexer-lib/src/graphql/parser.rs
  packages/fuel-indexer-lib/src/graphql/validator.rs
  packages/fuel-indexer-lib/src/lib.rs
  packages/fuel-indexer-macros/src/constants.rs
  packages/fuel-indexer-macros/src/decoder.rs
  packages/fuel-indexer-macros/src/helpers.rs
  packages/fuel-indexer-schema/README.md
  packages/fuel-indexer-schema/src/db.rs
  packages/fuel-indexer-schema/src/db/manager.rs
  packages/fuel-indexer-schema/src/db/tables.rs
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-schema/src/utils.rs
  packages/fuel-indexer-tests/components/fuel-node/Cargo.toml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-types/src/fuel.rs
Labels: enhancement, graphql, explorer

#1068 fix: ensure that unions are added to query root
  packages/fuel-indexer-schema/src/db/tables.rs
Labels: bug, graphql, explorer

#1061 ci: add default indexer + examples ci
  .github/workflows/ci.yml
  ci/build-and-deploy-examples.bash
  ci/build-images.bash
  config.yaml
  packages/fuel-indexer-api-server/src/models.rs
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer-lib/src/utils.rs
  plugins/forc-index/src/defaults.rs
  plugins/forc-index/src/ops/forc_index_start.rs
Labels: ci

#1077 fix: wait for hello-world-node to build on ci
  ci/build-and-deploy-examples.bash
Labels: bug, ci

#1076 chore: Remove `QueryRoot` workaround
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-graphql/src/arguments.rs
  packages/fuel-indexer-graphql/src/dynamic.rs
  packages/fuel-indexer-graphql/src/graphql.rs
  packages/fuel-indexer-lib/src/graphql/parser.rs
  packages/fuel-indexer-macros/src/decoder.rs
  packages/fuel-indexer-schema/src/db/tables.rs
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-tests/tests/integration/graphql_schema.rs
Labels: graphql, code quality, chore

#1065 chore: add docker multiplatform
  .cargo/config
  .github/workflows/ci.yml
  deployment/Dockerfile
  examples/fuel-explorer/README.md
  examples/fuel-explorer/docker-compose.yaml
  examples/hello-world/README.md
  examples/hello-world/docker-compose.yaml
  examples/hello-world/hello-world-node/src/main.rs
Labels: ci

#1084 chore: remove `.expect()` from GraphQL query flow
  packages/fuel-indexer-graphql/src/graphql.rs
Labels: chore

#1089 Fix unreported WASM runtime error
  packages/fuel-indexer/src/executor.rs
Labels: bug, P: High

#1086 chore: re-enable TRYBUILD tests
  Cargo.lock
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-macros/src/lib.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.stderr
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.stderr
  packages/fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_multi_type.rs
  packages/fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_single_type.rs
Labels: chore

#1092 fix: dont panic on empty panicreceipt contract id
  examples/fuel-explorer/fuel-explorer/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
Labels: bug, P: High, explorer

#1088 fix: bump cursor when unique constraint fails due to ID derivation
  packages/fuel-indexer/src/executor.rs
Labels: bug

#1097 fix: prevent serde error from crashing service
  packages/fuel-indexer-macros/src/decoder.rs
  packages/fuel-indexer-types/src/fuel.rs
  packages/fuel-indexer/src/ffi.rs
Labels: bug

#1072 Update wasmer from v2.3.0 to v4.0.0
  Cargo.lock
  Cargo.toml
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/tests/integration/database.rs
  packages/fuel-indexer/Cargo.toml
  packages/fuel-indexer/src/database.rs
  packages/fuel-indexer/src/executor.rs
  packages/fuel-indexer/src/ffi.rs
  packages/fuel-indexer/src/lib.rs
Labels: enhancement, dependencies

#1104 docs: specify alternative darwin/arm64 docker image in docs
  examples/fuel-explorer/README.md
  examples/hello-world/README.md
Labels: documentation

#1102 chore: add more executor logging
  packages/fuel-indexer/src/executor.rs
Labels: chore

#1108 chore: fix docker multiplatform builds
  deployment/Dockerfile
Labels: ci, chore

#1109 docs: remove reference to temporary docker image
  examples/fuel-explorer/README.md
  examples/hello-world/README.md
Labels: documentation

#1113 chore: reduce CI run time for releases
  .github/workflows/ci.yml
Labels: ci, chore

#1116 fix: dispatch per block instead of per transaction
  packages/fuel-indexer-macros/src/indexer.rs
Labels: bug, P: High, codegen

#1117 v0.18.4
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
Labels: release

#1119 fix: re-add steps back to release
  .github/workflows/ci.yml
Labels: bug, ci

#1122 chore: bump MAX_ARRAY_LENGTH
  packages/fuel-indexer-lib/src/lib.rs
Labels: bug, chore

#1106 enhancement: add endpoint for raw sql queries
  Cargo.lock
  config.yaml
  deployment/charts/fuel-indexer/templates/fuel-indexer-deployment.yaml
  docs/src/forc-index/start.md
  docs/src/getting-started/starting-the-fuel-indexer.md
  docs/src/graphql/api-server.md
  docs/src/queries/index.md
  examples/fuel-explorer/docker-compose.yaml
  examples/hello-world/docker-compose.yaml
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-api-server/src/commands/run.rs
  packages/fuel-indexer-api-server/src/lib.rs
  packages/fuel-indexer-api-server/src/models.rs
  packages/fuel-indexer-api-server/src/sql.rs
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-lib/src/config/cli.rs
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-lib/src/config/web.rs
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-plugin/src/native.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/e2e/graphql_api_postgres.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/tests/e2e/mod.rs
  packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs
  packages/fuel-indexer/src/commands/run.rs
  packages/fuel-indexer/src/lib.rs
  plugins/forc-index/src/cli.rs
  plugins/forc-index/src/commands/check.rs
  plugins/forc-index/src/commands/kill.rs
  plugins/forc-index/src/defaults.rs
  plugins/forc-index/src/ops/forc_index_start.rs
  plugins/forc-index/src/ops/forc_index_welcome.rs
  scripts/docker-compose.yaml
Labels: enhancement, breaking

#1126 chore: refactor manifest usage + refactor tests
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-lib/Cargo.toml
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-lib/src/graphql/mod.rs
  packages/fuel-indexer-lib/src/lib.rs
  packages/fuel-indexer-lib/src/manifest.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-schema/src/db/manager.rs
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/src/lib.rs
  packages/fuel-indexer-tests/tests/e2e/graphql_api_postgres.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/tests/integration/database.rs
  packages/fuel-indexer-tests/tests/integration/service.rs
  packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs
  packages/fuel-indexer/src/commands/run.rs
  packages/fuel-indexer/src/database.rs
  packages/fuel-indexer/src/executor.rs
  packages/fuel-indexer/src/service.rs
  plugins/forc-index-tests/Cargo.toml
  plugins/forc-index-tests/tests/commands.rs
  plugins/forc-index-tests/tests/mod.rs
  plugins/forc-index/src/ops/forc_index_build.rs
  plugins/forc-index/src/ops/forc_index_deploy.rs
  plugins/forc-index/src/ops/forc_index_remove.rs
Labels: code quality, chore

#1129 enhancement: add micro-benchmarking
  Cargo.lock
  packages/fuel-indexer-benchmarks/Cargo.toml
  packages/fuel-indexer-benchmarks/README.md
  packages/fuel-indexer-benchmarks/benches/graphql.rs
  packages/fuel-indexer-benchmarks/benches/wasm/examples/fuel_explorer.rs
  packages/fuel-indexer-benchmarks/benches/wasm/examples/mod.rs
  packages/fuel-indexer-benchmarks/benches/wasm/main.rs
  packages/fuel-indexer-benchmarks/benches/wasm_metering_benchmark.rs
  packages/fuel-indexer-benchmarks/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer/src/executor.rs
  packages/fuel-indexer/src/lib.rs
Labels: enhancement

#1132 ci: add cargo check
  .github/workflows/ci.yml
Labels: ci

#1133 fix: fix manifest creation in benchmarks
  packages/fuel-indexer-benchmarks/benches/wasm/examples/fuel_explorer.rs
  packages/fuel-indexer-benchmarks/src/lib.rs
Labels: bug

#1136 fix: add sql endpoint auth + make `run_query` fail gracefully
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-database/postgres/src/lib.rs
Labels: bug

#1138 chore: switch to manual sqlx query logging
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-database/src/lib.rs
  packages/fuel-indexer-lib/src/utils.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/tests/integration/database.rs
  packages/fuel-indexer/src/database.rs
  packages/fuel-indexer/src/executor.rs
Labels: chore

#1141 fix: update readme
  docs/README.md
  docs/src/authentication/index.md
  docs/src/forc-index/deploy.md
  docs/src/forc-index/remove.md
  docs/src/forc-index/status.md
  plugins/forc-index/README.md
Labels: bug, documentation

#1147 enhancement: make `NODE_BLOCK_PAGE_SIZE` configurable
  config.yaml
  deployment/charts/fuel-indexer/templates/fuel-indexer-deployment.yaml
  docs/src/getting-started/starting-the-fuel-indexer.md
  packages/fuel-indexer-lib/src/config/cli.rs
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer/src/executor.rs
Labels: documentation, enhancement

#1148 Replace blocking `reqwest` usage with async
  Cargo.lock
  plugins/forc-index/Cargo.toml
  plugins/forc-index/src/cli.rs
  plugins/forc-index/src/commands/auth.rs
  plugins/forc-index/src/commands/deploy.rs
  plugins/forc-index/src/commands/remove.rs
  plugins/forc-index/src/ops/forc_index_auth.rs
  plugins/forc-index/src/ops/forc_index_deploy.rs
  plugins/forc-index/src/ops/forc_index_remove.rs
  plugins/forc-index/src/ops/forc_index_welcome.rs
  plugins/forc-index/src/utils.rs
Labels: plugin

#1153 docs: adjust docs to include `--block-page-size` on start commands
  docs/src/forc-index/start.md
  docs/src/getting-started/starting-the-fuel-indexer.md
Labels: documentation

#1152 Replace blocking `reqwest` usage with async
  Cargo.lock
  plugins/forc-index/Cargo.toml
  plugins/forc-index/src/cli.rs
  plugins/forc-index/src/commands/auth.rs
  plugins/forc-index/src/commands/deploy.rs
  plugins/forc-index/src/commands/remove.rs
  plugins/forc-index/src/ops/forc_index_auth.rs
  plugins/forc-index/src/ops/forc_index_deploy.rs
  plugins/forc-index/src/ops/forc_index_remove.rs
  plugins/forc-index/src/ops/forc_index_welcome.rs
  plugins/forc-index/src/utils.rs
Labels: plugin

#1154 fix: don't skip blocks on constraint error
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/fuel_indexer_test.yaml
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/Forc.lock
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test.bin
  packages/fuel-indexer-tests/tests/e2e/graphql_api_postgres.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer/src/executor.rs
Labels: bug

#1161 docs: update non-book docs
  .markdownlintrc
  docs/CONTRIBUTING.md
  docs/PULL_REQUEST_TEMPLATE.md
  docs/README.md
  docs/RELEASE_SCHEDULE.md
  docs/src/forc-index/pull-abi.md
  docs/src/getting-started/quickstart.md
  examples/fuel-explorer/README.md
  examples/hello-world-native/README.md
  examples/hello-world/README.md
  plugins/forc-index/src/cli.rs
  plugins/forc-index/src/commands/mod.rs
  plugins/forc-index/src/commands/pull_abi.rs
  plugins/forc-index/src/commands/welcome.rs
  plugins/forc-index/src/defaults.rs
  plugins/forc-index/src/ops/forc_index_init.rs
  plugins/forc-index/src/ops/forc_index_pull_abi.rs
  plugins/forc-index/src/ops/forc_index_welcome.rs
  plugins/forc-index/src/ops/mod.rs
Labels: documentation, chore
