Repository FuelLabs/fuel-indexer, pull requests merged in 2023-08, with the labels that each got.

#1158 add docs CI
  .github/workflows/ci.yml
  .markdownlint.yaml
  .markdownlintignore
  .markdownlintrc
  docs/CONTRIBUTING.md
  docs/README.md
  docs/img/fuel-indexer-logo-dark.png
  docs/img/fuel-indexer-logo-light.png
  docs/img/fuel_indexer_flow.svg
  docs/src/SUMMARY.md
  docs/src/for-contributors/contributing-standards.md
  docs/src/for-contributors/release-schedule.md
  docs/src/forc-index/auth.md
  docs/src/getting-started/dependencies.md
  docs/src/getting-started/quickstart.md
  docs/src/graphql/playground.md
  docs/src/indexing/blocks-and-transactions.md
  docs/src/indexing/call.md
  docs/src/indexing/log.md
  docs/src/indexing/logdata.md
  docs/src/indexing/messageout.md
  docs/src/indexing/panic.md
  docs/src/indexing/return.md
  docs/src/indexing/returndata.md
  docs/src/indexing/revert.md
  docs/src/indexing/scriptresult.md
  docs/src/indexing/transfer.md
  docs/src/indexing/transferout.md
  docs/src/project-components/manifest.md
Labels: documentation, ci

#1140 enhancement: implement many-to-many relationships
  Cargo.lock
  examples/fuel-explorer/fuel-explorer/schema/fuel_explorer.schema.graphql
  examples/fuel-explorer/fuel-explorer/src/lib.rs
  packages/fuel-indexer-database/database-types/Cargo.toml
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-database/src/queries.rs
  packages/fuel-indexer-lib/src/graphql/mod.rs
  packages/fuel-indexer-lib/src/graphql/parser.rs
  packages/fuel-indexer-lib/src/lib.rs
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-macros/src/decoder.rs
  packages/fuel-indexer-plugin/src/lib.rs
  packages/fuel-indexer-plugin/src/native.rs
  packages/fuel-indexer-plugin/src/wasm.rs
  packages/fuel-indexer-schema/src/db/tables.rs
  packages/fuel-indexer-schema/src/join.rs
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer/src/database.rs
  packages/fuel-indexer/src/executor.rs
  packages/fuel-indexer/src/ffi.rs
Labels: enhancement, explorer

#1142 chore: improve UX of `forc index` plugin commands
  .github/workflows/ci.yml
  Cargo.lock
  docs/README.md
  docs/src/forc-index/build.md
  docs/src/forc-index/check.md
  docs/src/forc-index/deploy.md
  docs/src/forc-index/init.md
  docs/src/forc-index/kill.md
  docs/src/forc-index/new.md
  docs/src/getting-started/quickstart.md
  packages/fuel-indexer-lib/src/config/cli.rs
  plugins/forc-index/Cargo.toml
  plugins/forc-index/README.md
  plugins/forc-index/src/cli.rs
  plugins/forc-index/src/commands/build.rs
  plugins/forc-index/src/commands/check.rs
  plugins/forc-index/src/commands/deploy.rs
  plugins/forc-index/src/commands/init.rs
  plugins/forc-index/src/commands/mod.rs
  plugins/forc-index/src/commands/new.rs
  plugins/forc-index/src/defaults.rs
  plugins/forc-index/src/ops/forc_index_build.rs
  plugins/forc-index/src/ops/forc_index_check.rs
  plugins/forc-index/src/ops/forc_index_deploy.rs
  plugins/forc-index/src/ops/forc_index_init.rs
  plugins/forc-index/src/ops/forc_index_new.rs
  plugins/forc-index/src/ops/forc_index_status.rs
  plugins/forc-index/src/ops/mod.rs
  plugins/forc-postgres/src/commands/create.rs
Labels: chore, devx

#1166 ci: streamline develop <> master merges
  .github/workflows/ci.yml
  docs/PULL_REQUEST_TEMPLATE.md
  packages/fuel-indexer-benchmarks/src/lib.rs
  packages/fuel-indexer/src/executor.rs
Labels: ci

#1172 v0.19.0
  Cargo.lock
  Cargo.toml
  plugins/forc-index/src/defaults.rs
Labels: release

#1184 fix: trigger publish/docker on master & release
  .github/workflows/ci.yml
Labels: bug

#1185 fix: trigger publish/docker on master & release (again)
  .github/workflows/ci.yml
Labels: bug, ci

#1195 ci: update latest docker tag
  .github/workflows/ci.yml
Labels: ci

#1200 v0.19.1
  Cargo.lock
  Cargo.toml
Labels: release

#1190 chore: code cleanup + add indices to explorer
  .github/workflows/ci.yml
  Cargo.lock
  ci/build-and-deploy-examples.bash
  config.yaml
  examples/fuel-explorer/README.md
  examples/fuel-explorer/fuel-explorer/fuel_explorer.manifest.yaml
  examples/fuel-explorer/fuel-explorer/schema/fuel_explorer.schema.graphql
  examples/hello-world-native/README.md
  examples/hello-world-native/hello-indexer-native/hello_indexer_native.manifest.yaml
  examples/hello-world-native/hello-indexer-native/src/main.rs
  examples/hello-world/README.md
  examples/hello-world/hello-indexer/hello_indexer.manifest.yaml
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-database/src/queries.rs
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer-lib/src/graphql/mod.rs
  packages/fuel-indexer-macros/src/decoder.rs
  packages/fuel-indexer-macros/src/helpers.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-plugin/src/native.rs
  packages/fuel-indexer-schema/src/db/manager.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/tests/integration/database.rs
  packages/fuel-indexer/src/database.rs
  packages/fuel-indexer/src/executor.rs
  packages/fuel-indexer/src/service.rs
  scripts/utils/build_modules.bash
Labels: breaking, chore

#1204 fix: fail gracefully on web api
  Cargo.lock
  examples/fuel-explorer/docker-compose.yaml
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
Labels: chore

#1202 enhancement/breaking: update directive usage
  docs/src/data-types/types.md
  docs/src/database/foreign-keys.md
  docs/src/graphql/directives.md
  docs/src/project-components/schema.md
  docs/src/queries/index.md
  examples/fuel-explorer/fuel-explorer/schema/fuel_explorer.schema.graphql
  examples/hello-world-native/hello-indexer-native/schema/hello_indexer_native.schema.graphql
  examples/hello-world/hello-indexer/schema/hello_indexer.schema.graphql
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-graphql/src/graphql.rs
  packages/fuel-indexer-lib/src/graphql/mod.rs
  packages/fuel-indexer-lib/src/graphql/parser.rs
  packages/fuel-indexer-macros/src/decoder.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/simple-wasm/bad_simple_wasm.graphql
  packages/fuel-indexer-tests/components/indices/simple-wasm/schema/schema.graphql
  packages/fuel-indexer-tests/components/indices/simple-wasm/schema/simple_wasm.graphql
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/tests/integration/graphql_schema.rs
  plugins/forc-index/src/defaults.rs
Labels: documentation, enhancement, book, breaking

#1210 v0.19.2
  Cargo.lock
  Cargo.toml
  deployment/charts/fuel-indexer/templates/fuel-indexer-deployment.yaml
Labels: release

#1219 fix: temporarily skip bad ids
  packages/fuel-indexer/src/executor.rs
Labels: bug

#1220 v0.19.3
  Cargo.lock
  Cargo.toml
Labels: release

#1224 ci: only publish docker on release
  .github/workflows/ci.yml
Labels: ci

#1222 log message for start block when resumable not set
  packages/fuel-indexer/src/service.rs
Labels: enhancement

#1236 fix: update + explain executor logic
  packages/fuel-indexer-benchmarks/src/lib.rs
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer-lib/src/manifest.rs
  packages/fuel-indexer-tests/tests/e2e/graphql_api_postgres.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer/src/executor.rs
  packages/fuel-indexer/src/lib.rs
  packages/fuel-indexer/src/service.rs
  plugins/forc-index/src/ops/forc_index_build.rs
Labels: bug

#1249 v0.19.4
  Cargo.lock
  Cargo.toml
Labels: release

#1192 chore: upgrade to beta-4 dependencies
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  deployment/Dockerfile
  examples/fuel-explorer/fuel-explorer/schema/fuel_explorer.schema.graphql
  examples/fuel-explorer/fuel-explorer/src/lib.rs
  examples/hello-world-native/hello-indexer-native/schema/hello_indexer_native.schema.graphql
  examples/hello-world-native/hello-indexer-native/src/main.rs
  examples/hello-world/hello-indexer/schema/hello_indexer.schema.graphql
  examples/hello-world/hello-world-data/Cargo.toml
  packages/fuel-indexer-benchmarks/Cargo.toml
  packages/fuel-indexer-benchmarks/src/lib.rs
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-database/src/queries.rs
  packages/fuel-indexer-lib/src/graphql/mod.rs
  packages/fuel-indexer-lib/src/manifest.rs
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/fuel_indexer_test.yaml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/tests/integration/service.rs
  packages/fuel-indexer-types/src/fuel.rs
  packages/fuel-indexer-types/src/scalar.rs
  packages/fuel-indexer/Cargo.toml
  packages/fuel-indexer/assets/schema.sdl
  packages/fuel-indexer/src/executor.rs
  packages/fuel-indexer/src/queries.rs
  packages/fuel-indexer/src/service.rs
  plugins/forc-index/src/defaults.rs
Labels: P: High

#1259 enhancement: add support for `Mint` and `Burn` receipts
  docs/src/SUMMARY.md
  docs/src/indexing/burn.md
  docs/src/indexing/mint.md
  docs/src/indexing/receipts.md
  packages/fuel-indexer-lib/src/graphql/constants.rs
  packages/fuel-indexer-macros/src/constants.rs
  packages/fuel-indexer-macros/src/helpers.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/fuel_indexer_test.yaml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/Forc.lock
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/Forc.toml
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test-abi.json
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test.bin
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/src/main.sw
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-types/src/fuel.rs
  packages/fuel-indexer-types/src/receipt.rs
  packages/fuel-indexer-types/src/scalar.rs
Labels: documentation, P: High

#1268 fix: add debug info to error log
  packages/fuel-indexer/src/executor.rs
Labels: bug

#1271 fix: add `OPTIONS` to allowed CORS methods
  packages/fuel-indexer-api-server/src/api.rs
Labels: bug

#1272 v0.19.5
  Cargo.lock
  Cargo.toml
Labels: release

#1267 docs: add issue template
  .markdownlintignore
  docs/ISSUE_TEMPLATE.md
Labels: documentation

#1283 v0.20.0
  Cargo.lock
  Cargo.toml
  plugins/forc-index/src/defaults.rs
Labels: release

#1284 fix: remove cyclic dep
  .github/workflows/ci.yml
  Cargo.lock
  docs/README.md
  docs/src/for-contributors/index.md
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-macros/src/lib.rs
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/indexers/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/src/lib.rs
  packages/fuel-indexer-tests/tests/lib.rs
  packages/fuel-indexer-tests/tests/trybuild.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.stderr
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.stderr
Labels: bug

#1285 chore: fix docs + turn tests back on + fix naming
  .github/workflows/ci.yml
  ci/test-examples.bash
  docs/README.md
  docs/src/for-contributors/index.md
  plugins/forc-index/src/defaults.rs
Labels: bug

#1286 v0.20.1
  Cargo.lock
  Cargo.toml
Labels: release

#1287 fix: re-enable docker publish on master + re-enable plugin tests
  .github/workflows/ci.yml
Labels: bug

#1294 fix: update `MessageOut` data parsing
  .github/workflows/ci.yml
  Cargo.toml
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer/Cargo.toml
Labels: bug

#1298 v0.20.3
  Cargo.lock
  Cargo.toml
Labels: release

#1304 v0.20.4
  Cargo.lock
  Cargo.toml
Labels: release

#1313 fix: update MessageOut data parsing due to API change
  packages/fuel-indexer-macros/src/indexer.rs
Labels: bug

#1315 fix: fix overly broad tuple type check
  examples/hello-world/contracts/greeting/Forc.lock
  examples/hello-world/contracts/greeting/out/debug/greeting-abi.json
  examples/hello-world/contracts/greeting/out/debug/greeting.bin
  packages/fuel-indexer-macros/src/helpers.rs
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/Forc.lock
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/Forc.toml
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test.bin
  packages/fuel-indexer-tests/contracts/simple-wasm/Forc.lock
  packages/fuel-indexer-tests/indexers/fuel-indexer-test/fuel_indexer_test.yaml
  packages/fuel-indexer-tests/indexers/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/tests/indexing.rs
Labels: bug

#1319 v0.20.6
  Cargo.lock
  Cargo.toml
Labels: release

#1323 v0.20.7
  Cargo.lock
  Cargo.toml
Labels: release
