Repository FuelLabs/fuel-indexer, pull requests merged in 2023-03, with the labels that each got.

#627 chore: set workspace dependencies and change packages to use them
  Cargo.toml
  examples/block-explorer/explorer-index/Cargo.toml
  examples/hello-world-native/hello-index-native/Cargo.toml
  examples/hello-world/hello-index/Cargo.toml
  examples/hello-world/hello-world-data/Cargo.toml
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-database/Cargo.toml
  packages/fuel-indexer-database/database-types/Cargo.toml
  packages/fuel-indexer-database/postgres/Cargo.toml
  packages/fuel-indexer-lib/Cargo.toml
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-metrics/Cargo.toml
  packages/fuel-indexer-plugin/Cargo.toml
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple-wasm/Cargo.toml
  packages/fuel-indexer-types/Cargo.toml
  packages/fuel-indexer/Cargo.toml
  plugins/forc-index/Cargo.toml
  plugins/forc-postgres/Cargo.toml
Labels: code quality, chore

#623 ci: streamline ci
  .github/workflows/ci.yml
  Cargo.lock
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-api-server/src/lib.rs
  packages/fuel-indexer-database/Cargo.toml
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-database/src/lib.rs
  packages/fuel-indexer-lib/src/lib.rs
  packages/fuel-indexer-metrics/src/lib.rs
  packages/fuel-indexer-plugin/src/lib.rs
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer/Cargo.toml
  packages/fuel-indexer/src/lib.rs
Labels: ci

#622 enhancement: support foreign keys and nested queries in graphql api
  Cargo.lock
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-schema/src/db/graphql.rs
  packages/fuel-indexer-schema/src/db/tables.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/fuel_indexer_test.yaml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test-abi.json
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test.bin
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/src/main.sw
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/src/lib.rs
  packages/fuel-indexer-tests/tests/e2e/graphql_api_postgres.rs
  packages/fuel-indexer-tests/tests/integration/graphql_schema.rs
Labels: enhancement, graphql, big

#629 fix: deploy contract from hello-world-node
  examples/hello-world/hello-index/hello_index.manifest.yaml
  examples/hello-world/hello-world-data/src/main.rs
  examples/hello-world/hello-world-node/src/main.rs
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
Labels: bug

#633 chore: add fuel-core to indexer release builds
  .github/workflows/ci.yml
  deployment/Dockerfile
Labels: infrastructure, ci

#636 docs: make docs friendlier to first-time users
  docs/src/SUMMARY.md
  docs/src/examples/block-explorer.md
  docs/src/examples/hello-world.md
  docs/src/reference-guide/components/assets/module.md
  docs/src/reference-guide/indexing/blocks-and-transactions.md
  docs/src/reference-guide/indexing/receipts.md
  docs/src/reference-guide/indexing/receipts/index.md
  docs/src/reference-guide/indexing/what-can-i-index.md
Labels: documentation

#639 docs: update readme with m1 wasm info
  docs/README.md
Labels: documentation

#640 fix: kill old execution module when redeploying under same namespace and identifier
  packages/fuel-indexer/src/service.rs
Labels: bug

#632 enhancement: add functionality for automatic database creation and start to `forc-index`
  Cargo.lock
  docs/README.md
  docs/src/SUMMARY.md
  docs/src/quickstart/index.md
  docs/src/reference-guide/plugins/forc-index/start.md
  docs/src/reference-guide/plugins/forc-postgres/create.md
  docs/src/reference-guide/plugins/forc-postgres/drop.md
  docs/src/reference-guide/plugins/forc-postgres/index.md
  docs/src/reference-guide/plugins/forc-postgres/start.md
  docs/src/reference-guide/plugins/forc-postgres/stop.md
  docs/src/reference-guide/plugins/index.md
  packages/fuel-indexer-lib/src/config/mod.rs
  plugins/forc-index/Cargo.toml
  plugins/forc-index/src/cli.rs
  plugins/forc-index/src/commands/start.rs
  plugins/forc-index/src/ops/forc_index_start.rs
  plugins/forc-postgres/Cargo.toml
  plugins/forc-postgres/src/commands/create.rs
  plugins/forc-postgres/src/ops/forc_postgres_createdb.rs
  plugins/forc-postgres/src/ops/forc_postgres_startdb.rs
  plugins/forc-postgres/src/pg.rs
Labels: documentation, enhancement, plugin, devx

#609 enhancement: add `forc index revert` command
  docs/src/reference-guide/plugins/forc-index/index.md
  examples/block-explorer/explorer-index/src/lib.rs
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-database/src/queries.rs
  packages/fuel-indexer-lib/src/utils.rs
  packages/fuel-indexer-metrics/src/queries/postgres.rs
  packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs
  packages/fuel-indexer/src/service.rs
  plugins/forc-index/README.md
  plugins/forc-index/src/cli.rs
  plugins/forc-index/src/commands/mod.rs
  plugins/forc-index/src/commands/revert.rs
  plugins/forc-index/src/ops/forc_index_init.rs
  plugins/forc-index/src/ops/forc_index_revert.rs
  plugins/forc-index/src/ops/mod.rs
Labels: enhancement, plugin

#595 enhancement: add resume index functionality
  docs/src/reference-guide/components/assets/manifest.md
  examples/block-explorer/explorer-index/explorer_index.manifest.yaml
  examples/hello-world-native/hello_index_native.manifest.yaml
  examples/hello-world/hello-index/hello_index.manifest.yaml
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-database/src/queries.rs
  packages/fuel-indexer-lib/src/manifest.rs
  packages/fuel-indexer-metrics/src/queries/postgres.rs
  packages/fuel-indexer-tests/assets/simple_wasm.wasm
  packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs
  packages/fuel-indexer/src/executor.rs
  packages/fuel-indexer/src/service.rs
  plugins/forc-index/src/utils/defaults.rs
Labels: enhancement, code quality

#653 ci: use buildjet runners
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  examples/block-explorer/explorer-index/Cargo.toml
  examples/hello-world-native/hello-index-native/Cargo.toml
  examples/hello-world/hello-index/Cargo.toml
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-metrics/Cargo.toml
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/components/fuel-node/Cargo.toml
  plugins/forc-postgres/Cargo.toml
  tomlfmt.toml
Labels: ci

#630 enhancement: indexer authentication
  Cargo.lock
  config.yaml
  docs/src/SUMMARY.md
  docs/src/getting-started/starting-the-fuel-indexer.md
  docs/src/reference-guide/authentication/index.md
  docs/src/reference-guide/plugins/forc-index/auth.md
  examples/hello-world/hello-world-data/src/main.rs
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-api-server/src/auth.rs
  packages/fuel-indexer-api-server/src/commands/run.rs
  packages/fuel-indexer-api-server/src/lib.rs
  packages/fuel-indexer-api-server/src/models.rs
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-database/postgres/Cargo.toml
  packages/fuel-indexer-database/postgres/migrations/20220909082511_create_asset_registry.down.sql
  packages/fuel-indexer-database/postgres/migrations/20220909082511_create_asset_registry.up.sql
  packages/fuel-indexer-database/postgres/migrations/20230303134345_create_table_nonce.down.sql
  packages/fuel-indexer-database/postgres/migrations/20230303134345_create_table_nonce.up.sql
  packages/fuel-indexer-database/postgres/migrations/20230311134345_add_auth_to_index_registry.down.sql
  packages/fuel-indexer-database/postgres/migrations/20230311134345_add_auth_to_index_registry.up.sql
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-database/src/queries.rs
  packages/fuel-indexer-lib/src/config/auth.rs
  packages/fuel-indexer-lib/src/config/database.rs
  packages/fuel-indexer-lib/src/config/fuel_node.rs
  packages/fuel-indexer-lib/src/config/graphql.rs
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer-metrics/src/queries/postgres.rs
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/src/lib.rs
  packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs
  packages/fuel-indexer/src/commands/run.rs
  packages/fuel-indexer/src/service.rs
  plugins/forc-index/Cargo.toml
  plugins/forc-index/src/cli.rs
  plugins/forc-index/src/commands/auth.rs
  plugins/forc-index/src/commands/build.rs
  plugins/forc-index/src/commands/deploy.rs
  plugins/forc-index/src/commands/mod.rs
  plugins/forc-index/src/ops/forc_index_auth.rs
  plugins/forc-index/src/ops/forc_index_check.rs
  plugins/forc-index/src/ops/forc_index_deploy.rs
  plugins/forc-index/src/ops/forc_index_remove.rs
  plugins/forc-index/src/ops/forc_index_start.rs
  plugins/forc-index/src/ops/mod.rs
Labels: enhancement, big, work in progress

#652 chore: remove sqlx query_as
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
Labels: code quality, chore, devx

#658 chore: add function to get test contract ID from binary file
  examples/hello-world/hello-world-data/src/main.rs
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/Forc.lock
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/src/lib.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
Labels: testing, blocked, chore

#644 docs: documentation refresh for milestone
  docs/README.md
  docs/src/SUMMARY.md
  docs/src/examples/block-explorer.md
  docs/src/examples/hello-world.md
  docs/src/for-contributors/contributing-standards.md
  docs/src/for-contributors/index.md
  docs/src/for-contributors/release-schedule.md
  docs/src/getting-started/dependencies.md
  docs/src/getting-started/dependencies/database.md
  docs/src/getting-started/dependencies/fuelup.md
  docs/src/getting-started/dependencies/index.md
  docs/src/getting-started/dependencies/wasm.md
  docs/src/getting-started/index.md
  docs/src/getting-started/starting-the-fuel-indexer.md
  docs/src/glossary.md
  docs/src/img/fuel-indexer-logo-dark.png
  docs/src/img/fuel-indexer-logo-light.png
  docs/src/img/fuel.png
  docs/src/quickstart/index.md
  docs/src/reference-guide/components/assets/index.md
  docs/src/reference-guide/components/assets/manifest.md
  docs/src/reference-guide/components/assets/module.md
  docs/src/reference-guide/components/database/ids.md
  docs/src/reference-guide/components/database/index.md
  docs/src/reference-guide/components/database/types.md
  docs/src/reference-guide/components/fuel-indexer-project.md
  docs/src/reference-guide/components/graphql/directives.md
  docs/src/reference-guide/components/graphql/index.md
  docs/src/reference-guide/components/graphql/queries.md
  docs/src/reference-guide/components/graphql/schema.md
  docs/src/reference-guide/components/index.md
  docs/src/reference-guide/components/indices/index.md
  docs/src/reference-guide/components/indices/registration.md
  docs/src/reference-guide/data-types/types.md
  docs/src/reference-guide/indexing/receipts/call.md
  docs/src/reference-guide/indexing/receipts/log.md
  docs/src/reference-guide/indexing/receipts/logdata.md
  docs/src/reference-guide/indexing/receipts/messageout.md
  docs/src/reference-guide/indexing/receipts/return.md
  docs/src/reference-guide/indexing/receipts/returndata.md
  docs/src/reference-guide/indexing/receipts/scriptresult.md
  docs/src/reference-guide/indexing/receipts/transfer.md
  docs/src/reference-guide/indexing/receipts/transferout.md
  docs/src/reference-guide/plugins/forc-index/deploy.md
  docs/src/reference-guide/plugins/forc-index/index.md
  docs/src/reference-guide/plugins/forc-index/new.md
  docs/src/reference-guide/plugins/forc-index/remove.md
  docs/src/reference-guide/plugins/forc-index/revert.md
  docs/src/reference-guide/plugins/index.md
  docs/src/the-fuel-indexer.md
  plugins/forc-index/README.md
Labels: documentation

#661 chore: update examples `hello-index` -> `hello-indexer`
  Cargo.lock
  Cargo.toml
  docs/README.md
  docs/src/examples/hello-world.md
  docs/src/reference-guide/components/fuel-indexer-project.md
  examples/block-explorer/explorer-index/explorer_index.manifest.yaml
  examples/block-explorer/explorer-indexer/.cargo/config
  examples/block-explorer/explorer-indexer/Cargo.toml
  examples/block-explorer/explorer-indexer/explorer_indexer.manifest.yaml
  examples/block-explorer/explorer-indexer/schema/explorer_indexer.schema.graphql
  examples/block-explorer/explorer-indexer/src/lib.rs
  examples/hello-world-native/hello-indexer-native/Cargo.toml
  examples/hello-world-native/hello-indexer-native/schema/hello_indexer_native.schema.graphql
  examples/hello-world-native/hello-indexer-native/src/main.rs
  examples/hello-world-native/hello_indexer_native.manifest.yaml
  examples/hello-world/README.md
  examples/hello-world/hello-indexer/.cargo/config
  examples/hello-world/hello-indexer/Cargo.toml
  examples/hello-world/hello-indexer/hello_indexer.manifest.yaml
  examples/hello-world/hello-indexer/schema/hello_indexer.schema.graphql
  examples/hello-world/hello-indexer/src/lib.rs
  scripts/utils/build_test_wasm_module.bash
Labels: documentation, code quality, examples

#665 docs: fix block explorer embed in book
  docs/src/examples/block-explorer.md
Labels: documentation

#667 v0.5.0
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  plugins/forc-index/src/utils/defaults.rs
Labels: release

#670 fix: update ci bool syntax
  .github/workflows/ci.yml
Labels: bug, ci

#672 fix: remove skipped dependent jobs for master/release
  .github/workflows/ci.yml
Labels: bug, ci

#674 remove --fuel-core-lib from Dockerfile
  .github/workflows/ci.yml
  deployment/Dockerfile
Labels: bug, ci

#675 ci: remove Postgres service from cargo-verifications build step
  .github/workflows/ci.yml
Labels: ci

#678 ops: update deployment start cmd
  deployment/charts/templates/fuel-indexer-deployment.yaml
Labels: infrastructure

#679 fix: ci publish tag verification
  .github/workflows/ci.yml
Labels: bug, ci

#686 docs: update docs
  docs/README.md
  docs/src/reference-guide/authentication/index.md
  docs/src/reference-guide/plugins/forc-index/build.md
  docs/src/reference-guide/plugins/forc-index/deploy.md
  docs/src/reference-guide/plugins/forc-index/init.md
  docs/src/reference-guide/plugins/forc-index/new.md
  docs/src/reference-guide/plugins/forc-index/remove.md
  docs/src/reference-guide/plugins/forc-index/revert.md
  plugins/forc-index/README.md
  plugins/forc-index/src/commands/auth.rs
  plugins/forc-index/src/commands/build.rs
  plugins/forc-index/src/commands/deploy.rs
  plugins/forc-index/src/commands/init.rs
  plugins/forc-index/src/commands/new.rs
  plugins/forc-index/src/commands/remove.rs
  plugins/forc-index/src/commands/revert.rs
  plugins/forc-index/src/ops/forc_index_init.rs
Labels: documentation, book

#659 chore: use verbose in plugins
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-metrics/src/queries/postgres.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  plugins/forc-index/src/cli.rs
  plugins/forc-index/src/commands/build.rs
  plugins/forc-index/src/commands/deploy.rs
  plugins/forc-index/src/commands/init.rs
  plugins/forc-index/src/commands/new.rs
  plugins/forc-index/src/commands/remove.rs
  plugins/forc-index/src/commands/revert.rs
  plugins/forc-index/src/ops/forc_index_auth.rs
  plugins/forc-index/src/ops/forc_index_build.rs
  plugins/forc-index/src/ops/forc_index_check.rs
  plugins/forc-index/src/ops/forc_index_deploy.rs
  plugins/forc-index/src/ops/forc_index_init.rs
  plugins/forc-index/src/ops/forc_index_new.rs
  plugins/forc-index/src/ops/forc_index_remove.rs
  plugins/forc-index/src/ops/forc_index_revert.rs
  plugins/forc-index/src/ops/forc_index_start.rs
  plugins/forc-postgres/src/commands/create.rs
  plugins/forc-postgres/src/commands/drop.rs
  plugins/forc-postgres/src/commands/start.rs
  plugins/forc-postgres/src/commands/stop.rs
  plugins/forc-postgres/src/ops/forc_postgres_createdb.rs
  plugins/forc-postgres/src/ops/forc_postgres_dropdb.rs
  plugins/forc-postgres/src/ops/forc_postgres_startdb.rs
  plugins/forc-postgres/src/ops/forc_postgres_stopdb.rs
Labels: plugin, devx

#676 chore: cleanup plugin command opts
  Cargo.lock
  deployment/charts/templates/fuel-indexer-deployment.yaml
  docs/src/reference-guide/plugins/forc-index/build.md
  docs/src/reference-guide/plugins/forc-index/deploy.md
  docs/src/reference-guide/plugins/forc-index/init.md
  docs/src/reference-guide/plugins/forc-index/new.md
  docs/src/reference-guide/plugins/forc-index/remove.md
  docs/src/reference-guide/plugins/forc-index/revert.md
  docs/src/reference-guide/plugins/forc-index/start.md
  examples/block-explorer/README.md
  examples/block-explorer/explorer-indexer/Cargo.toml
  examples/hello-world-native/hello-indexer-native/Cargo.toml
  examples/hello-world/README.md
  examples/hello-world/hello-indexer/Cargo.toml
  examples/hello-world/hello-indexer/hello_indexer.manifest.yaml
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  plugins/forc-index/src/commands/build.rs
  plugins/forc-index/src/commands/deploy.rs
  plugins/forc-index/src/commands/new.rs
  plugins/forc-index/src/commands/remove.rs
  plugins/forc-index/src/commands/revert.rs
  plugins/forc-index/src/ops/forc_index_build.rs
  plugins/forc-index/src/ops/forc_index_deploy.rs
  plugins/forc-index/src/utils/defaults.rs
  plugins/forc-index/src/utils/mod.rs
  scripts/utils/build_test_wasm_module.bash
Labels: code quality, breaking, plugin

#690 docs: update documentation for `Call` receipt
  docs/src/reference-guide/indexing/receipts/call.md
Labels: documentation, book

#601 chore: update docs to beta-3
  docs/README.md
  docs/src/reference-guide/components/fuel-node.md
  examples/block-explorer/docker-compose.yaml
Labels: documentation, book

#691 chore: general plugin cleanup
  config.yaml
  docs/README.md
  docs/src/examples/block-explorer.md
  docs/src/for-contributors/index.md
  docs/src/getting-started/dependencies/database.md
  docs/src/getting-started/starting-the-fuel-indexer.md
  docs/src/quickstart/index.md
  docs/src/reference-guide/components/fuel-node.md
  docs/src/reference-guide/components/graphql/api-server.md
  docs/src/reference-guide/components/graphql/queries.md
  docs/src/reference-guide/plugins/forc-index/auth.md
  docs/src/reference-guide/plugins/forc-index/check.md
  docs/src/reference-guide/plugins/forc-index/deploy.md
  docs/src/reference-guide/plugins/forc-index/remove.md
  docs/src/reference-guide/plugins/forc-index/revert.md
  docs/src/reference-guide/plugins/forc-index/start.md
  examples/block-explorer/README.md
  examples/block-explorer/docker-compose.yaml
  examples/hello-world/README.md
  examples/hello-world/hello-indexer/hello_indexer.manifest.yaml
  packages/fuel-indexer-lib/src/config/fuel_node.rs
  packages/fuel-indexer-lib/src/config/graphql.rs
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer-lib/src/utils.rs
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/src/lib.rs
  packages/fuel-indexer-tests/tests/e2e/graphql_api_postgres.rs
  packages/fuel-indexer-tests/tests/integration/database.rs
  packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs
  plugins/forc-index/src/ops/forc_index_check.rs
  plugins/forc-index/src/ops/forc_index_start.rs
  plugins/forc-index/src/utils/defaults.rs
  scripts/utils/refresh_test_db.bash
Labels: bug, documentation, plugin

#694 fix: update fuel-node fixture
  packages/fuel-indexer-tests/src/fixtures.rs
Labels: bug, testing

#700 v0.6.0
  Cargo.lock
  Cargo.toml
  plugins/forc-index/src/utils/defaults.rs
Labels: release

#706 chore: iterate blocks in proper ascending order
  packages/fuel-indexer/src/executor.rs
Labels: chore

#710 docs: fix typo
  docs/src/reference-guide/components/assets/module.md
Labels: documentation

#705 fix: do not panic when there is an empty data field in `MessageOut` receipt
  packages/fuel-indexer-macros/src/indexer.rs
Labels: bug, P: Medium, code quality

#711 v0.6.1
  Cargo.lock
  Cargo.toml
Labels: release

#689 enhancement: support revert receipts
  docs/src/SUMMARY.md
  docs/src/reference-guide/indexing/receipts.md
  docs/src/reference-guide/indexing/receipts/revert.md
  packages/fuel-indexer-macros/src/constant.rs
  packages/fuel-indexer-macros/src/helpers.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/fuel_indexer_test.yaml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test-abi.json
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test.bin
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/src/main.sw
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-types/src/abi.rs
Labels: enhancement, book

#714 enhancement: support panic receipts
  docs/src/SUMMARY.md
  docs/src/reference-guide/indexing/receipts/panic.md
  docs/src/reference-guide/indexing/receipts/revert.md
  packages/fuel-indexer-macros/src/constant.rs
  packages/fuel-indexer-macros/src/helpers.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/fuel_indexer_test.yaml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test-abi.json
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test.bin
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/src/main.sw
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-types/src/abi.rs
Labels: documentation, enhancement

#718 chore: upgrade `wasmer` to v2.3.0
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer/Cargo.toml
Labels: dependencies, chore
