Repository FuelLabs/fuel-indexer, pull requests merged in 2023-01, with the labels that each got.

#454 fix: add wasm-snip to forc index build
  docs/src/examples/hello-world.md
  docs/src/quickstart/index.md
  examples/block-explorer/explorer-index/src/lib.rs
  examples/block-explorer/explorer_index.manifest.yaml
  examples/block-explorer/schema/explorer_index.schema.graphql
  examples/hello-world/hello-index/src/lib.rs
  examples/hello-world/hello_index.manifest.yaml
  packages/fuel-indexer-lib/src/utils.rs
  packages/fuel-indexer-plugin/src/lib.rs
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-tests/assets/explorer_index.wasm
  packages/fuel-indexer-tests/assets/hello_index.wasm
  packages/fuel-indexer-tests/components/fuel-node/src/main.rs
  plugins/forc-index/src/commands/init.rs
  plugins/forc-index/src/commands/new.rs
  plugins/forc-index/src/ops/forc_index_build.rs
  plugins/forc-index/src/ops/forc_index_check.rs
  plugins/forc-index/src/ops/forc_index_init.rs
  plugins/forc-index/src/ops/forc_index_start.rs
  plugins/forc-index/src/utils/defaults.rs
  scripts/utils/build_test_wasm_module.bash
  scripts/utils/refresh_test_db.bash
Labels: bug, plugin

#462 enhancement (fuel-indexer-tests): Add tests for asset upload
  Cargo.lock
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/src/lib.rs
  packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs
  packages/fuel-indexer-tests/tests/integration/web_api_sqlite.rs
Labels: testing

#465 enhancement: add support for blob type
  Cargo.lock
  docs/src/components/database/types.md
  examples/hello-world/hello-index/src/lib.rs
  examples/hello-world/schema/hello_index.schema.graphql
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-plugin/Cargo.toml
  packages/fuel-indexer-plugin/src/wasm.rs
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-schema/src/base.graphql
  packages/fuel-indexer-schema/src/db/tables.rs
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-tests/assets/explorer_index.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/assets/hello_index.wasm
  packages/fuel-indexer-tests/assets/simple_wasm.wasm
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_sqlite.rs
  packages/fuel-indexer-types/src/lib.rs
Labels: enhancement

#463 enhancement, fix (fuel-indexer-macros): Adjustments to `Return` and `ReturnData` receipt handling
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-macros/src/wasm.rs
  packages/fuel-indexer-plugin/src/native.rs
  packages/fuel-indexer-plugin/src/wasm.rs
  packages/fuel-indexer-types/src/abi.rs
Labels: bug, P: High

#467 Remove actions-rs in favor of built-in `cargo` and `rustup`
  .github/workflows/ci.yml
Labels: ci

#469 enhancement: forc index build prereq to forc index deploy
  plugins/forc-index/src/commands/deploy.rs
  plugins/forc-index/src/ops/forc_index_deploy.rs
Labels: enhancement, plugin

#457 fix: contract_id param in manifest
  docs/README.md
  docs/src/quickstart/index.md
  examples/block-explorer/explorer_index.manifest.yaml
  examples/hello-world-native/hello_index_native.manifest.yaml
  examples/hello-world/hello_index.manifest.yaml
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-macros/src/wasm.rs
  packages/fuel-indexer-tests/assets/explorer_index.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.yaml
  packages/fuel-indexer-tests/assets/hello_index.wasm
  packages/fuel-indexer-tests/assets/simple_wasm.wasm
  packages/fuel-indexer-types/src/lib.rs
  packages/fuel-indexer/src/service.rs
  plugins/forc-index/src/ops/forc_index_deploy.rs
  plugins/forc-index/src/utils/defaults.rs
Labels: bug

#470 Add release doc
  docs/RELEASE_SCHEDULE.md
Labels: documentation

#471 v0.1.13
  .gitignore
  Cargo.lock
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-database/Cargo.toml
  packages/fuel-indexer-database/database-types/Cargo.toml
  packages/fuel-indexer-database/postgres/Cargo.toml
  packages/fuel-indexer-database/sqlite/Cargo.toml
  packages/fuel-indexer-lib/Cargo.toml
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-metrics/Cargo.toml
  packages/fuel-indexer-plugin/Cargo.toml
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-types/Cargo.toml
  packages/fuel-indexer/Cargo.toml
  plugins/forc-index/Cargo.toml
Labels: release

#472 fix (CI): Remove `--target` flag from `cargo install cross`
  .github/workflows/ci.yml
Labels: bug, ci

#473 fix (CI): Re-add cargo-install action to install `cross`
  .github/workflows/ci.yml
Labels: bug, ci

#474 revert: #467,#472,#473
  .github/workflows/ci.yml
Labels: ci

#475 enhancement: add cors + tracing middleware
  Cargo.lock
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-api-server/src/api.rs
Labels: enhancement

#476 enhancement (fuel-indexer-tests): Add tests for start block
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_sqlite.rs
Labels: testing

#477 docs: update contrib doc
  docs/CONTRIBUTING.md
Labels: documentation

#479 chore: add hash to explorer-index
  examples/block-explorer/explorer-index/src/lib.rs
  examples/block-explorer/schema/explorer_index.schema.graphql
  packages/fuel-indexer-tests/assets/explorer_index.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/assets/hello_index.wasm
  packages/fuel-indexer-tests/assets/simple_wasm.wasm
Labels: chore

#486 docs: update quickstart
  docs/src/SUMMARY.md
  docs/src/quickstart/index.md
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-lib/src/config/graphql.rs
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-lib/src/defaults.rs
  plugins/forc-index/src/cli.rs
  plugins/forc-index/src/commands/check.rs
  plugins/forc-index/src/commands/deploy.rs
  plugins/forc-index/src/commands/remove.rs
  plugins/forc-index/src/commands/start.rs
  plugins/forc-index/src/ops/forc_index_init.rs
  plugins/forc-index/src/ops/forc_index_start.rs
  plugins/forc-index/src/utils/defaults.rs
  scripts/docker-compose.yaml
Labels: documentation, book

#487 fix: refactor service to retire futs
  Cargo.lock
  examples/hello-world-native/hello-index-native/src/main.rs
  examples/hello-world-native/schema/hello_index_native.schema.graphql
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer/Cargo.toml
  packages/fuel-indexer/src/database.rs
  packages/fuel-indexer/src/executor.rs
  packages/fuel-indexer/src/service.rs
Labels: bug

#500 chore: move indexer createion to executors
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer/src/executor.rs
  packages/fuel-indexer/src/service.rs
  plugins/forc-index/src/commands/start.rs
Labels: code quality

#505 chore: cleanup test index
  examples/block-explorer/explorer_index.manifest.yaml
  examples/hello-world/hello_index.manifest.yaml
  packages/fuel-indexer-tests/assets/explorer_index.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/assets/hello_index.wasm
  packages/fuel-indexer-tests/assets/simple_wasm.wasm
  packages/fuel-indexer-tests/assets/wallet.json
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_sqlite.rs
  packages/fuel-indexer/src/executor.rs
  scripts/utils/build_test_wasm_module.bash
Labels: chore

#506 enhancement: add tuple support
  Cargo.lock
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-tests/assets/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.yaml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test-abi.json
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test.bin
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/src/main.sw
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/src/lib.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_sqlite.rs
Labels: enhancement

#508 chore: version bump to v0.2.0
  Cargo.lock
  examples/block-explorer/explorer-index/Cargo.toml
  examples/hello-world-native/hello-index-native/Cargo.toml
  examples/hello-world/hello-bin/Cargo.toml
  examples/hello-world/hello-index/Cargo.toml
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-database/Cargo.toml
  packages/fuel-indexer-database/database-types/Cargo.toml
  packages/fuel-indexer-database/postgres/Cargo.toml
  packages/fuel-indexer-database/sqlite/Cargo.toml
  packages/fuel-indexer-lib/Cargo.toml
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-metrics/Cargo.toml
  packages/fuel-indexer-plugin/Cargo.toml
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple-wasm/Cargo.toml
  packages/fuel-indexer-types/Cargo.toml
  packages/fuel-indexer/Cargo.toml
  plugins/forc-index/Cargo.toml
  plugins/forc-index/src/utils/defaults.rs
Labels: release

#507 docs: update readme
  docs/README.md
Labels: documentation

#509 chore: simplify forc-index check
  docs/README.md
  docs/src/quickstart/index.md
  plugins/forc-index/src/ops/forc_index_check.rs
Labels: chore, plugin

#514 fix: various forc index fixes
  docs/README.md
  docs/src/quickstart/index.md
  plugins/forc-index/src/ops/forc_index_check.rs
  plugins/forc-index/src/utils/defaults.rs
  scripts/docker-compose.yaml
Labels: bug, documentation, plugin

#527 chore: update notify slack action version
  .github/workflows/ci.yml
Labels: ci

#531 chore: upgrade to rustc 1.67
  examples/hello-world/hello-bin/src/main.rs
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-database/sqlite/src/lib.rs
  packages/fuel-indexer-database/src/lib.rs
  packages/fuel-indexer-lib/src/config/database.rs
  packages/fuel-indexer-lib/src/config/fuel_node.rs
  packages/fuel-indexer-lib/src/config/graphql.rs
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-lib/src/utils.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-schema/src/db/graphql.rs
  packages/fuel-indexer-schema/src/db/tables.rs
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-schema/src/utils.rs
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/src/lib.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_sqlite.rs
  packages/fuel-indexer-tests/tests/integration/graphql_schema.rs
  packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs
  packages/fuel-indexer-tests/tests/integration/web_api_sqlite.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.stderr
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.stderr
  packages/fuel-indexer-types/src/abi.rs
  packages/fuel-indexer-types/src/lib.rs
  packages/fuel-indexer/src/database.rs
  packages/fuel-indexer/src/executor.rs
  packages/fuel-indexer/src/ffi.rs
  plugins/forc-index/src/ops/forc_index_build.rs
  plugins/forc-index/src/ops/forc_index_check.rs
  plugins/forc-index/src/ops/forc_index_init.rs
Labels: chore

#523 Update docs to include additional dependencies and clear up info regarding docker
  docs/README.md
Labels: good first issue, dependencies

#534 chore: bump docker base to rustc 1.67
  deployment/Dockerfile
Labels: infrastructure, chore

#533 docs: fix book build
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  docs/src/SUMMARY.md
Labels: ci, book

#532 docs: small book updates + update compose
  docs/README.md
  docs/src/SUMMARY.md
  docs/src/for-contributors/building-from-source.md
  docs/src/getting-started/dependencies/fuelup.md
  docs/src/getting-started/dependencies/wasm-snip.md
  docs/src/getting-started/dependencies/wasm.md
  docs/src/getting-started/starting-the-fuel-indexer.md
  docs/src/quickstart/index.md
  docs/src/reference-guide/components/database/foreign-keys.md
  docs/src/reference-guide/indexing/blocks-and-transactions.md
  docs/src/reference-guide/indexing/receipts/index.md
  docs/src/the-fuel-indexer.md
Labels: documentation, book

#536 v0.2.1
  Cargo.lock
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-database/Cargo.toml
  packages/fuel-indexer-database/database-types/Cargo.toml
  packages/fuel-indexer-database/postgres/Cargo.toml
  packages/fuel-indexer-database/sqlite/Cargo.toml
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-metrics/Cargo.toml
  packages/fuel-indexer-plugin/Cargo.toml
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-types/Cargo.toml
  packages/fuel-indexer/Cargo.toml
  plugins/forc-index/Cargo.toml
Labels: release

#538 v0.2.2
  Cargo.lock
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-database/Cargo.toml
  packages/fuel-indexer-database/database-types/Cargo.toml
  packages/fuel-indexer-database/postgres/Cargo.toml
  packages/fuel-indexer-database/sqlite/Cargo.toml
  packages/fuel-indexer-lib/Cargo.toml
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-metrics/Cargo.toml
  packages/fuel-indexer-plugin/Cargo.toml
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-types/Cargo.toml
  packages/fuel-indexer/Cargo.toml
  plugins/forc-index/Cargo.toml
Labels: release

#539 chore: add `build.rs` files for docs.rs
  packages/fuel-indexer-database/postgres/build.rs
  packages/fuel-indexer-database/sqlite/build.rs
Labels: documentation, chore
