Repository FuelLabs/fuel-indexer, pull requests merged in 2023-04, with the labels that each got.

#687 enhancement: make verbose logging configurable
  config.yaml
  deployment/charts/templates/fuel-indexer-deployment.yaml
  docs/src/getting-started/starting-the-fuel-indexer.md
  docs/src/reference-guide/components/graphql/api-server.md
  packages/fuel-indexer-api-server/src/cli.rs
  packages/fuel-indexer-api-server/src/commands/run.rs
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-database/src/lib.rs
  packages/fuel-indexer-lib/src/config/database.rs
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer-lib/src/utils.rs
  packages/fuel-indexer-plugin/src/lib.rs
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer/src/cli.rs
  packages/fuel-indexer/src/commands/run.rs
  packages/fuel-indexer/src/service.rs
  plugins/forc-index/src/ops/forc_index_start.rs
  plugins/forc-postgres/src/ops/forc_postgres_createdb.rs
Labels: enhancement, devx

#713 chore: executor creation cleanup
  Cargo.lock
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer-lib/src/manifest.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer/Cargo.toml
  packages/fuel-indexer/src/executor.rs
  packages/fuel-indexer/src/service.rs
Labels: code quality, chore

#726 chore: fix CI commands for plugin tests
  .github/workflows/ci.yml
Labels: ci, chore

#728 chore: update quickstart
  docs/QUICKSTART.md
  docs/README.md
  docs/src/quickstart/index.md
Labels: documentation, book, chore

#730 fix: persist embedded db when flag is passed
  plugins/forc-index/src/ops/forc_index_start.rs
Labels: bug

#731 fix: add fuel-core-lib feature to binary
  .github/workflows/ci.yml
  config.yaml
  deployment/Dockerfile
  docs/src/getting-started/starting-the-fuel-indexer.md
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer/src/commands/run.rs
  plugins/forc-index/src/ops/forc_index_start.rs
Labels: ci

#736 ci: switch back to github runners
  .github/workflows/ci.yml
Labels: ci

#733 chore: small auth devx updates
  config.yaml
  packages/fuel-indexer-lib/src/config/auth.rs
  packages/fuel-indexer-lib/src/config/mod.rs
  plugins/forc-index/src/ops/forc_index_auth.rs
  plugins/forc-index/src/ops/forc_index_deploy.rs
Labels: chore

#735 v0.7.0
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  plugins/forc-index/src/utils/defaults.rs
Labels: release

#742 fix: await fuel-core service when using --local-fuel-node
  packages/fuel-indexer-tests/tests/e2e/graphql_api_postgres.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/tests/integration/service.rs
  packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs
  packages/fuel-indexer-tests/tests/lib.rs
  packages/fuel-indexer/src/commands/run.rs
  plugins/forc-index/src/ops/forc_index_auth.rs
Labels: bug, code quality

#738 ci: remove merge queue
  .github/workflows/ci.yml
Labels: ci

#717 enhancement: support graphql-playground
  Cargo.lock
  docs/QUICKSTART.md
  docs/src/SUMMARY.md
  docs/src/examples/block-explorer.md
  docs/src/reference-guide/components/graphql/playground.md
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/tests/e2e/graphql_api_postgres.rs
Labels: enhancement, graphql, devx

#744 enhancement: compute message ID by using `MessageOut` receipt fields
  Cargo.lock
  examples/block-explorer/explorer-indexer/Cargo.toml
  examples/hello-world-native/hello-indexer-native/Cargo.toml
  examples/hello-world/hello-indexer/Cargo.toml
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-macros/src/native.rs
  packages/fuel-indexer-macros/src/wasm.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple-wasm/Cargo.toml
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
Labels: bug, enhancement

#747 chore: fix dependency location for message ID calculation
  Cargo.lock
  examples/block-explorer/explorer-indexer/Cargo.toml
  examples/hello-world-native/hello-indexer-native/Cargo.toml
  examples/hello-world/hello-indexer/Cargo.toml
  packages/fuel-indexer-plugin/Cargo.toml
  packages/fuel-indexer-plugin/src/native.rs
  packages/fuel-indexer-plugin/src/wasm.rs
Labels: chore

#745 chore: add rust-doc to fuel-indexer-lib
  packages/fuel-indexer-lib/src/config/auth.rs
  packages/fuel-indexer-lib/src/config/database.rs
  packages/fuel-indexer-lib/src/config/graphql.rs
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-lib/src/config/node.rs
  packages/fuel-indexer-lib/src/config/utils.rs
  packages/fuel-indexer-lib/src/lib.rs
  packages/fuel-indexer-lib/src/manifest.rs
  packages/fuel-indexer-tests/src/lib.rs
  plugins/forc-index/src/ops/forc_index_deploy.rs
Labels: documentation, chore

#729 enhancement: allow network config from manifest
  .github/workflows/ci.yml
  config.yaml
  docs/QUICKSTART.md
  docs/src/getting-started/starting-the-fuel-indexer.md
  docs/src/reference-guide/components/assets/manifest.md
  examples/block-explorer/explorer-indexer/explorer_indexer.manifest.yaml
  examples/hello-world-native/hello-indexer-native/hello_indexer_native.manifest.yaml
  examples/hello-world/hello-indexer/hello_indexer.manifest.yaml
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer-lib/src/manifest.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/fuel_indexer_test.yaml
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer/src/executor.rs
  packages/fuel-indexer/src/lib.rs
Labels: enhancement

#752 v0.8.0
  Cargo.lock
  Cargo.toml
  plugins/forc-index/src/utils/defaults.rs
Labels: release

#751 fix: don't panic on deploy that results in 401
  examples/block-explorer/explorer-indexer/explorer_indexer.manifest.yaml
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  plugins/forc-index/src/ops/forc_index_deploy.rs
Labels: bug

#758 fix: decode auth signature before recovery
  Cargo.lock
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-api-server/src/uses.rs
  plugins/forc-index/src/ops/forc_index_auth.rs
Labels: bug

#743 docs: various documentation improvements
  docs/QUICKSTART.md
  docs/README.md
  docs/src/reference-guide/authentication/index.md
  docs/src/reference-guide/components/graphql/playground.md
  packages/fuel-indexer-api-server/src/lib.rs
Labels: documentation, book

#719 enhancement: support many contracts one manifest
  Cargo.lock
  docs/src/reference-guide/components/assets/manifest.md
  packages/fuel-indexer-lib/Cargo.toml
  packages/fuel-indexer-lib/src/manifest.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/bad_simple_wasm.yaml
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.yaml
Labels: enhancement

#764 v0.9.0
  Cargo.lock
  Cargo.toml
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  plugins/forc-index/src/utils/defaults.rs
Labels: release

#761 enhancement: add `PageInfo` object to paginated GraphQL responses
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-schema/src/db/arguments.rs
  packages/fuel-indexer-schema/src/db/graphql.rs
  packages/fuel-indexer-schema/src/db/queries.rs
  packages/fuel-indexer-tests/tests/e2e/graphql_api_postgres.rs
  packages/fuel-indexer-tests/tests/integration/graphql_schema.rs
Labels: enhancement, graphql

#765 fix: run migrations in docker compose
  examples/block-explorer/docker-compose.yaml
  examples/hello-world/docker-compose.yaml
Labels: bug

#762 chore: bump fuels to `v0.40.0`
  Cargo.lock
  examples/block-explorer/explorer-indexer/Cargo.toml
  examples/hello-world-native/hello-indexer-native/Cargo.toml
  examples/hello-world/hello-indexer/Cargo.toml
  examples/hello-world/hello-world-data/Cargo.toml
  examples/hello-world/hello-world-data/src/main.rs
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-macros/src/native.rs
  packages/fuel-indexer-macros/src/wasm.rs
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/components/fuel-node/Cargo.toml
  packages/fuel-indexer-tests/components/fuel-node/src/main.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/fuel_indexer_test.yaml
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple-wasm/Cargo.toml
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/Forc.lock
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test.bin
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/tests/integration/database.rs
  packages/fuel-indexer-tests/tests/integration/service.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.rs
  packages/fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_multi_type.rs
  packages/fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_single_type.rs
  packages/fuel-indexer-types/Cargo.toml
  packages/fuel-indexer-types/src/abi.rs
  packages/fuel-indexer-types/src/lib.rs
  plugins/forc-index/Cargo.toml
  plugins/forc-index/src/utils/defaults.rs
Labels: dependencies, chore

#769 docs: swap link for copy/paste of m1 text in book
  docs/src/getting-started/dependencies/wasm.md
Labels: book

#631 enhancement: welcome plugin
  Cargo.lock
  packages/fuel-indexer-lib/src/config/mod.rs
  plugins/forc-index/Cargo.toml
  plugins/forc-index/src/cli.rs
  plugins/forc-index/src/commands/build.rs
  plugins/forc-index/src/commands/deploy.rs
  plugins/forc-index/src/commands/mod.rs
  plugins/forc-index/src/commands/welcome.rs
  plugins/forc-index/src/ops/forc_index_init.rs
  plugins/forc-index/src/ops/forc_index_welcome.rs
  plugins/forc-index/src/ops/mod.rs
  plugins/forc-index/src/utils/defaults.rs
Labels: enhancement, plugin

#771 chore: deprecate `actions-rs` for `dtolnay/rust-toolchain`
  .github/workflows/ci.yml
Labels: ci

#779 fix: hide JWT secret from debug info
  packages/fuel-indexer-lib/src/config/auth.rs
Labels: bug

#772 fix: correct usage of `fuel-indexer` feature flags
  examples/block-explorer/docker-compose.yaml
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-api-server/src/commands/run.rs
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/e2e/graphql_api_postgres.rs
  packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs
  packages/fuel-indexer/src/commands/run.rs
  packages/fuel-indexer/src/service.rs
  plugins/forc-index/src/utils/defaults.rs
Labels: bug

#778 enhancement: Add graphQL info output when indexer runs
  packages/fuel-indexer/src/commands/run.rs
Labels: enhancement

#781 fix: include proper graphql config key name
  packages/fuel-indexer-lib/src/config/mod.rs
Labels: bug

#783 v0.10.0
  Cargo.lock
  Cargo.toml
  plugins/forc-index/src/utils/defaults.rs
Labels: release

#785 enhancement: add prometheus metrics middleware
  Cargo.lock
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-api-server/src/lib.rs
  packages/fuel-indexer-api-server/src/middleware/auth.rs
  packages/fuel-indexer-api-server/src/middleware/metrics.rs
  packages/fuel-indexer-api-server/src/middleware/mod.rs
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-metrics/Cargo.toml
  packages/fuel-indexer-metrics/src/core.rs
  packages/fuel-indexer-metrics/src/db/mod.rs
  packages/fuel-indexer-metrics/src/db/postgres.rs
  packages/fuel-indexer-metrics/src/lib.rs
  packages/fuel-indexer-metrics/src/queries/mod.rs
  packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs
  plugins/forc-index/src/utils/defaults.rs
Labels: enhancement, infrastructure

#753 enhancement: support sway error enums
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/fuel_indexer_test.yaml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test-abi.json
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test.bin
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/src/main.sw
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
Labels: enhancement

#802 fix: log schema api error
  packages/fuel-indexer-api-server/src/api.rs
Labels: bug

#804 chore: switch metrics over to base deployment
  deployment/charts/fuel-indexer/templates/fuel-indexer-service-monitor.yaml
Labels: infrastructure, chore

#817 v0.11.0
  Cargo.lock
  Cargo.toml
  plugins/forc-index/src/utils/defaults.rs
Labels: release

#818 bug: fix feature flag on `fuel-indexer-schema` for `fuel-indexer-graphql`
  .github/workflows/ci.yml
  packages/fuel-indexer-graphql/Cargo.toml
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-plugin/Cargo.toml
Labels: bug, P: High, dependencies, blocking

#819 v0.11.1
  Cargo.lock
  Cargo.toml
Labels: release

#821 fix: add postgres package features
  Cargo.toml
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
Labels: bug

#806 docs: update for consistency
  docs/src/getting-started/dependencies/database.md
  docs/src/getting-started/dependencies/index.md
  docs/src/reference-guide/indexing/receipts/call.md
  docs/src/reference-guide/indexing/receipts/log.md
  docs/src/reference-guide/indexing/receipts/logdata.md
  docs/src/reference-guide/indexing/receipts/messageout.md
  docs/src/reference-guide/indexing/receipts/panic.md
  docs/src/reference-guide/indexing/receipts/return.md
  docs/src/reference-guide/indexing/receipts/returndata.md
  docs/src/reference-guide/indexing/receipts/revert.md
  docs/src/reference-guide/indexing/receipts/scriptresult.md
  docs/src/reference-guide/indexing/receipts/transfer.md
  docs/src/reference-guide/indexing/receipts/transferout.md
  packages/fuel-indexer-api-server/src/lib.rs
  packages/fuel-indexer-metrics/src/core.rs
Labels: documentation, book

#828 bugfix: fix deserialize bug on contract_id
  packages/fuel-indexer-lib/src/manifest.rs
Labels: bug

#830 v0.11.2
  Cargo.lock
  Cargo.toml
Labels: release
