Repository FuelLabs/fuel-indexer, pull requests merged in 2023-05, with the labels that each got.

#840 docs: small book improvements
  docs/src/SUMMARY.md
  docs/src/reference-guide/data-types/types.md
  docs/src/reference-guide/indexing/blocks-and-transactions.md
Labels: book

#844 chore: use `[default-members]` section in `Cargo.toml`
  Cargo.toml
Labels: code quality, chore, devx

#835 bugfix: try pinning toolchain version
  fuel-toolchain.toml
Labels: bug

#841 `auth` password input message
  docs/src/reference-guide/authentication/index.md
Labels: documentation

#839 enhancement: add histogram reporting to postgres
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  packages/fuel-indexer-database/Cargo.toml
  packages/fuel-indexer-database/postgres/Cargo.toml
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-macros/macro-utils/Cargo.toml
  packages/fuel-indexer-macros/macro-utils/src/lib.rs
  packages/fuel-indexer-macros/src/lib.rs
  packages/fuel-indexer-metrics/src/core.rs
  packages/fuel-indexer-metrics/src/db/mod.rs
  packages/fuel-indexer-metrics/src/db/postgres.rs
  packages/fuel-indexer-metrics/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs
Labels: enhancement

#845 enhancement: convert Scalar types into `Json` and `Blob`
  Cargo.lock
  examples/hello-world-native/hello-indexer-native/src/main.rs
  examples/hello-world/hello-indexer/src/lib.rs
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-types/Cargo.toml
  packages/fuel-indexer-types/src/lib.rs
Labels: enhancement, code quality, breaking

#848 fix: don't send wasm bytes over service channel
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-database/src/queries.rs
  packages/fuel-indexer-lib/src/utils.rs
  packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs
  packages/fuel-indexer/src/service.rs
Labels: bug

#850 chore: bump to rustc 1.69
  .github/workflows/ci.yml
  Cargo.toml
  deployment/Dockerfile
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs
Labels: dependencies, chore

#852 fix: update docs/examples
  ci/Dockerfile.fuel-node
  examples/hello-world-native/README.md
  examples/hello-world-native/hello-indexer-native/Cargo.toml
  examples/hello-world/README.md
  packages/fuel-indexer-lib/src/manifest.rs
  packages/fuel-indexer-macros/src/indexer.rs
  plugins/forc-index/src/ops/forc_index_deploy.rs
  plugins/forc-index/src/utils/defaults.rs
Labels: bug, documentation, work in progress

#861 v0.12.0
  Cargo.lock
  Cargo.toml
  plugins/forc-index/src/utils/defaults.rs
Labels: release

#824 enhancement: add end_block field in manifest
  docs/src/reference-guide/components/assets/manifest.md
  examples/block-explorer/explorer-indexer/explorer_indexer.manifest.yaml
  examples/hello-world-native/hello-indexer-native/hello_indexer_native.manifest.yaml
  examples/hello-world/hello-indexer/hello_indexer.manifest.yaml
  packages/fuel-indexer-lib/src/manifest.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/fuel_indexer_test.yaml
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer/src/executor.rs
Labels: documentation, enhancement

#866 v0.12.1
  Cargo.lock
  Cargo.toml
Labels: release

#868 chore: add end_block to default forc index manifest
  plugins/forc-index/src/utils/defaults.rs
Labels: documentation, plugin

#876 docs: add pr template
  docs/PULL_REQUEST.md
Labels: documentation, devx

#883 Docs: Update broken hyperlink
  docs/src/reference-guide/indexing/blocks-and-transactions.md
Labels: documentation

#775 enhancement: pull remote ABI subcommand
  docs/src/reference-guide/plugins/forc-index/pull-abi.md
  packages/fuel-indexer-tests/tests/e2e/examples.rs
  plugins/forc-index/src/cli.rs
  plugins/forc-index/src/commands/init.rs
  plugins/forc-index/src/commands/mod.rs
  plugins/forc-index/src/commands/pull_abi.rs
  plugins/forc-index/src/ops/forc_index_pull_abi.rs
  plugins/forc-index/src/ops/mod.rs
Labels: enhancement, plugin

#895 v0.13.0
  Cargo.lock
  Cargo.toml
  plugins/forc-index/src/utils/defaults.rs
Labels: release

#902 fix: remove query root + refactor graphql schema
  docs/README.md
  docs/src/reference-guide/components/database/foreign-keys.md
  docs/src/reference-guide/components/graphql/directives.md
  docs/src/reference-guide/components/graphql/queries/index.md
  docs/src/reference-guide/components/graphql/schema.md
  examples/block-explorer/explorer-indexer/schema/explorer_indexer.schema.graphql
  examples/hello-world-native/hello-indexer-native/schema/hello_indexer_native.schema.graphql
  examples/hello-world/hello-indexer/schema/hello_indexer.schema.graphql
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-database/postgres/migrations/20230512183030_remove_query_root.down.sql
  packages/fuel-indexer-database/postgres/migrations/20230512183030_remove_query_root.up.sql
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-graphql/src/graphql.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-schema/src/db.rs
  packages/fuel-indexer-schema/src/db/manager.rs
  packages/fuel-indexer-schema/src/db/tables.rs
  packages/fuel-indexer-schema/src/explorer.graphql
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-schema/src/utils.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/simple-wasm/bad_simple_wasm.graphql
  packages/fuel-indexer-tests/components/indices/simple-wasm/schema/schema.graphql
  packages/fuel-indexer-tests/components/indices/simple-wasm/schema/simple_wasm.graphql
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/tests/integration/graphql_schema.rs
  packages/fuel-indexer/src/lib.rs
  plugins/forc-index-tests/tests/commands.rs
  plugins/forc-index/src/utils/defaults.rs
Labels: bug, graphql, breaking, work in progress

#910 docs: add GraphQL functionality table
  docs/README.md
  docs/src/reference-guide/components/graphql/index.md
Labels: documentation

#926 fix: introspection response was nested one level too deep
  packages/fuel-indexer-graphql/src/dynamic.rs
Labels: bug, graphql

#756 enhancement: add playground constraints
  Cargo.lock
  config.yaml
  deployment/charts/fuel-indexer/templates/fuel-indexer-deployment.yaml
  docs/src/examples/block-explorer.md
  docs/src/getting-started/starting-the-fuel-indexer.md
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-lib/src/config/auth.rs
  packages/fuel-indexer-lib/src/config/database.rs
  packages/fuel-indexer-lib/src/config/graphql.rs
  packages/fuel-indexer-lib/src/config/limit.rs
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-lib/src/config/node.rs
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer-lib/src/utils.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/fuel_indexer_test.yaml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/Forc.lock
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test.bin
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer/src/cli.rs
  packages/fuel-indexer/src/executor.rs
  packages/fuel-indexer/src/lib.rs
  plugins/forc-index/src/ops/forc_index_welcome.rs
Labels: enhancement

#927 fix: remove duplicate start arg
  deployment/charts/fuel-indexer/templates/fuel-indexer-deployment.yaml
Labels: bug

#930 enhancement: add explorer types
  Cargo.lock
  Cargo.toml
  examples/block-explorer/explorer-indexer/Cargo.toml
  examples/hello-world-native/hello-indexer-native/Cargo.toml
  examples/hello-world/hello-indexer/Cargo.toml
  examples/hello-world/hello-world-data/Cargo.toml
  packages/fuel-indexer-database/database-types/Cargo.toml
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-graphql/src/dynamic.rs
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-schema/src/base.graphql
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/components/fuel-node/Cargo.toml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple-wasm/Cargo.toml
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/components/web-api/Cargo.toml
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-types/Cargo.toml
  packages/fuel-indexer-types/src/abi.rs
  packages/fuel-indexer-types/src/lib.rs
  packages/fuel-indexer-types/src/tx.rs
  plugins/forc-index/Cargo.toml
  plugins/forc-index/src/utils/defaults.rs
Labels: enhancement, explorer

#872 enhancement: add graphql enum support
  Cargo.lock
  Cargo.toml
  examples/block-explorer/explorer-indexer/Cargo.toml
  examples/block-explorer/explorer-indexer/schema/explorer_indexer.schema.graphql
  examples/block-explorer/explorer-indexer/src/lib.rs
  examples/fuel-explorer/fuel-explorer/Cargo.toml
  examples/hello-world-native/hello-indexer-native/Cargo.toml
  examples/hello-world/hello-indexer/Cargo.toml
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-database/postgres/Cargo.toml
  packages/fuel-indexer-database/postgres/migrations/20230519162647_add_virtual_columns_to_typeids.down.sql
  packages/fuel-indexer-database/postgres/migrations/20230519162647_add_virtual_columns_to_typeids.up.sql
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-graphql/src/dynamic.rs
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-macros/src/helpers.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-macros/src/native.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-macros/src/wasm.rs
  packages/fuel-indexer-plugin/Cargo.toml
  packages/fuel-indexer-plugin/src/lib.rs
  packages/fuel-indexer-plugin/src/native.rs
  packages/fuel-indexer-plugin/src/wasm.rs
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-schema/src/base.graphql
  packages/fuel-indexer-schema/src/db/manager.rs
  packages/fuel-indexer-schema/src/db/tables.rs
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-schema/src/parser.rs
  packages/fuel-indexer-schema/src/utils.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/fuel_indexer_test.yaml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple-wasm/Cargo.toml
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/Forc.lock
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test-abi.json
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test.bin
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/src/main.sw
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/e2e/graphql_api_postgres.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/tests/integration/database.rs
  packages/fuel-indexer-tests/tests/integration/service.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.stderr
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.stderr
  packages/fuel-indexer-types/src/lib.rs
  packages/fuel-indexer/Cargo.toml
  packages/fuel-indexer/src/commands/run.rs
  packages/fuel-indexer/src/service.rs
  plugins/forc-index/src/utils/defaults.rs
Labels: bug, enhancement, graphql

#924 chore: upgrade to syn v2.0
  Cargo.lock
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-macros/macro-utils/Cargo.toml
Labels: dependencies, chore

#942 fix: fix docs and schema type generation for playground
  Cargo.lock
  packages/fuel-indexer-graphql/src/dynamic.rs
  packages/fuel-indexer-graphql/src/graphql.rs
  packages/fuel-indexer-schema/src/db/tables.rs
  packages/fuel-indexer-tests/tests/integration/graphql_schema.rs
Labels: graphql, devx

#943 enhancement: add support for unindexable types
  Cargo.lock
  Cargo.toml
  examples/block-explorer/explorer-indexer/Cargo.toml
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-database/database-types/src/directives.rs
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-graphql/Cargo.toml
  packages/fuel-indexer-graphql/src/dynamic.rs
  packages/fuel-indexer-lib/Cargo.toml
  packages/fuel-indexer-lib/src/utils.rs
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-macros/src/native.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-macros/src/wasm.rs
  packages/fuel-indexer-plugin/Cargo.toml
  packages/fuel-indexer-plugin/src/lib.rs
  packages/fuel-indexer-plugin/src/wasm.rs
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-schema/src/base.graphql
  packages/fuel-indexer-schema/src/db/tables.rs
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-schema/src/parser.rs
  packages/fuel-indexer-schema/src/utils.rs
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/schema/fuel_indexer_test.graphql
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.stderr
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.stderr
  packages/fuel-indexer-types/src/graphql.rs
  packages/fuel-indexer-types/src/lib.rs
  packages/fuel-indexer/src/executor.rs
  plugins/forc-index/Cargo.toml
  plugins/forc-postgres/Cargo.toml
Labels: enhancement, graphql, explorer

#949 enhancement: implement more types
  docs/src/reference-guide/indexing/blocks-and-transactions.md
  examples/fuel-explorer/docker-compose.yaml
  examples/fuel-explorer/fuel-explorer/schema/fuel_explorer.schema.graphql
  examples/fuel-explorer/fuel-explorer/src/lib.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.stderr
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.stderr
  packages/fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_multi_type.rs
  packages/fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_single_type.rs
  packages/fuel-indexer-types/src/io.rs
  packages/fuel-indexer-types/src/lib.rs
  packages/fuel-indexer-types/src/transaction.rs
  packages/fuel-indexer/src/executor.rs
  scripts/docker-compose.yaml
Labels: enhancement, explorer

#952 v0.15.0
  Cargo.lock
  Cargo.toml
  plugins/forc-index/src/utils/defaults.rs
Labels: release

#954 fix: bump default indexer timeout + cleanup transaction creation in DB
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer/src/database.rs
  packages/fuel-indexer/src/executor.rs
Labels: bug

#955 v0.15.1
  Cargo.lock
  Cargo.toml
Labels: release

#957 fix: revert transactions on asset registration
  packages/fuel-indexer-api-server/src/uses.rs
Labels: bug

#948 docs: update example docs
  examples/hello-world-native/hello-indexer-native/src/main.rs
  examples/hello-world/hello-indexer/src/lib.rs
Labels: documentation

#956 enhancement: continue flushing out explorer
  examples/fuel-explorer/fuel-explorer/schema/fuel_explorer.schema.graphql
  examples/fuel-explorer/fuel-explorer/src/lib.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-plugin/src/lib.rs
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple_wasm.wasm
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.stderr
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.stderr
  packages/fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_multi_type.rs
  packages/fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_single_type.rs
  packages/fuel-indexer-types/src/block.rs
  packages/fuel-indexer-types/src/fuel.rs
  packages/fuel-indexer-types/src/io.rs
  packages/fuel-indexer-types/src/lib.rs
  packages/fuel-indexer-types/src/scalar.rs
  packages/fuel-indexer-types/src/transaction.rs
  packages/fuel-indexer/src/database.rs
  packages/fuel-indexer/src/executor.rs
  packages/fuel-indexer/src/service.rs
Labels: enhancement, explorer

#953 enhancement: re-export indexer `fuel-indexer-*` dependencies under `fuel-indexer-utils`
  Cargo.lock
  Cargo.toml
  examples/fuel-explorer/fuel-explorer/Cargo.toml
  examples/fuel-explorer/fuel-explorer/src/lib.rs
  examples/hello-world-native/hello-indexer-native/Cargo.toml
  examples/hello-world-native/hello-indexer-native/src/main.rs
  examples/hello-world/hello-indexer/Cargo.toml
  examples/hello-world/hello-indexer/src/lib.rs
  packages/fuel-indexer-lib/Cargo.toml
  packages/fuel-indexer-lib/src/utils.rs
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-macros/src/native.rs
  packages/fuel-indexer-macros/src/wasm.rs
  packages/fuel-indexer-plugin/src/lib.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple-wasm/Cargo.toml
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple-wasm/src/lib.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.stderr
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_args_include_self.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_args_include_self.stderr
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_args_not_included.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.stderr
  packages/fuel-indexer-tests/trybuild/fail_if_indexer_module_is_empty.rs
  packages/fuel-indexer-tests/trybuild/fail_if_indexer_module_is_empty.stderr
  packages/fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_multi_type.rs
  packages/fuel-indexer-tests/trybuild/pass_if_indexer_is_valid_single_type.rs
  packages/fuel-indexer-utils/Cargo.toml
  packages/fuel-indexer-utils/src/lib.rs
  packages/fuel-indexer-utils/src/utilities.rs
Labels: enhancement, devx, examples
