Repository FuelLabs/fuel-indexer, pull requests merged in 2023-02, with the labels that each got.

#547 chore: remove sqlite
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  config.yaml
  docs/CONTRIBUTING.md
  docs/README.md
  docs/src/for-contributors/index.md
  docs/src/getting-started/dependencies.md
  docs/src/getting-started/dependencies/database.md
  docs/src/getting-started/starting-the-fuel-indexer.md
  docs/src/reference-guide/components/database/foreign-keys.md
  docs/src/reference-guide/components/database/index.md
  docs/src/reference-guide/components/graphql/api-server.md
  docs/src/reference-guide/components/graphql/directives.md
  docs/src/reference-guide/data-types/types.md
  docs/src/reference-guide/plugins/forc-index/check.md
  packages/fuel-indexer-database/Cargo.toml
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-database/sqlite/.env
  packages/fuel-indexer-database/sqlite/Cargo.toml
  packages/fuel-indexer-database/sqlite/README.md
  packages/fuel-indexer-database/sqlite/build.rs
  packages/fuel-indexer-database/sqlite/migrations/.gitkeep
  packages/fuel-indexer-database/sqlite/migrations/20220713212919_initial_migration.down.sql
  packages/fuel-indexer-database/sqlite/migrations/20220713212919_initial_migration.up.sql
  packages/fuel-indexer-database/sqlite/migrations/2022090908251_create_asset_registry.down.sql
  packages/fuel-indexer-database/sqlite/migrations/2022090908251_create_asset_registry.up.sql
  packages/fuel-indexer-database/sqlite/sqlx-data.json
  packages/fuel-indexer-database/sqlite/src/lib.rs
  packages/fuel-indexer-database/src/lib.rs
  packages/fuel-indexer-database/src/queries.rs
  packages/fuel-indexer-lib/src/config/database.rs
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer-metrics/src/core.rs
  packages/fuel-indexer-metrics/src/queries/mod.rs
  packages/fuel-indexer-metrics/src/queries/sqlite.rs
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-schema/src/db/tables.rs
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/scripts/e2e.bash
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/e2e/graphql_api_sqlite.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_sqlite.rs
  packages/fuel-indexer-tests/tests/e2e/mod.rs
  packages/fuel-indexer-tests/tests/integration/database.rs
  packages/fuel-indexer-tests/tests/integration/mod.rs
  packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs
  packages/fuel-indexer-tests/tests/integration/web_api_sqlite.rs
  packages/fuel-indexer/Cargo.toml
  plugins/forc-index/src/commands/start.rs
  plugins/forc-index/src/ops/forc_index_check.rs
  plugins/forc-index/src/ops/forc_index_start.rs
  scripts/run_migrations.bash
  scripts/utils/refresh_test_db.bash
Labels: breaking, chore

#545 enhancement: update index namespacing
  examples/hello-world/README.md
  examples/hello-world/hello-index/hello_index.manifest.yaml
  packages/fuel-indexer-api-server/src/api.rs
  packages/fuel-indexer-api-server/src/uses.rs
  packages/fuel-indexer-database/database-types/src/lib.rs
  packages/fuel-indexer-database/postgres/migrations/20230131101109_alter-graph-registry-type-ids-add-identifier.down.sql
  packages/fuel-indexer-database/postgres/migrations/20230131101109_alter-graph-registry-type-ids-add-identifier.up.sql
  packages/fuel-indexer-database/postgres/src/lib.rs
  packages/fuel-indexer-database/src/queries.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-macros/src/schema.rs
  packages/fuel-indexer-schema/src/db/graphql.rs
  packages/fuel-indexer-schema/src/db/manager.rs
  packages/fuel-indexer-schema/src/db/tables.rs
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/assets/simple_wasm.wasm
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/tests/integration/database.rs
  packages/fuel-indexer-tests/tests/integration/graphql_schema.rs
  packages/fuel-indexer/src/database.rs
  packages/fuel-indexer/src/executor.rs
  packages/fuel-indexer/src/ffi.rs
  packages/fuel-indexer/src/service.rs
  scripts/utils/build_test_wasm_module.bash
Labels: enhancement, breaking

#550 enhancement: build docker images for x86_64, ARM, and M1 archs
  .github/workflows/ci.yml
Labels: enhancement, ci

#556 fix: update default indexer code
  plugins/forc-index/src/utils/defaults.rs
Labels: bug

#555 v0.2.3
  Cargo.lock
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-database/Cargo.toml
  packages/fuel-indexer-database/database-types/Cargo.toml
  packages/fuel-indexer-database/postgres/Cargo.toml
  packages/fuel-indexer-lib/Cargo.toml
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-metrics/Cargo.toml
  packages/fuel-indexer-plugin/Cargo.toml
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-types/Cargo.toml
  packages/fuel-indexer/Cargo.toml
  plugins/forc-index/Cargo.toml
Labels: release

#559 fix, docs: fix table on data types page
  docs/src/reference-guide/data-types/types.md
Labels: documentation, book

#557 ci: add simple CI check for `forc-index` plugin
  .github/workflows/ci.yml
Labels: ci, P: High

#554 ci: add check-rustc job
  .github/workflows/ci.yml
Labels: ci, dependencies

#562 fix: update quickstart docs
  docs/README.md
Labels: bug, documentation

#570 fix: test inconsistencies
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/assets/fuel_indexer_test.yaml
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test-abi.json
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test.bin
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/src/main.sw
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
Labels: testing

#569 chore, testing: build test WASM blobs in CI
  .github/workflows/ci.yml
  packages/fuel-indexer-tests/assets/fuel_indexer_test.wasm
  packages/fuel-indexer-tests/src/lib.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
Labels: ci, testing, P: Medium

#564 enhancement: add local-fuel-node arg to spin one up
  Cargo.lock
  packages/fuel-indexer/Cargo.toml
  packages/fuel-indexer/src/bin/fuel-indexer.rs
Labels: enhancement, devx

#551 enhancement: add subcommand invocation for fuel-indexer binaries
  Cargo.lock
  docs/src/for-contributors/index.md
  docs/src/getting-started/starting-the-fuel-indexer.md
  docs/src/reference-guide/components/graphql/api-server.md
  examples/hello-world-native/hello-index-native/src/main.rs
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-api-server/src/bin/fuel-indexer-api-server.rs
  packages/fuel-indexer-api-server/src/bin/main.rs
  packages/fuel-indexer-api-server/src/cli.rs
  packages/fuel-indexer-api-server/src/commands/mod.rs
  packages/fuel-indexer-api-server/src/commands/run.rs
  packages/fuel-indexer-api-server/src/lib.rs
  packages/fuel-indexer-lib/Cargo.toml
  packages/fuel-indexer-lib/src/config/mod.rs
  packages/fuel-indexer-lib/src/utils.rs
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-tests/components/web-api/Cargo.toml
  packages/fuel-indexer/Cargo.toml
  packages/fuel-indexer/src/bin/main.rs
  packages/fuel-indexer/src/cli.rs
  packages/fuel-indexer/src/commands/mod.rs
  packages/fuel-indexer/src/commands/run.rs
  packages/fuel-indexer/src/lib.rs
  plugins/forc-index/src/ops/forc_index_start.rs
Labels: enhancement, devx

#577 enhancement: forc index relative paths
  plugins/forc-index/src/commands/init.rs
  plugins/forc-index/src/commands/new.rs
  plugins/forc-index/src/ops/forc_index_init.rs
  plugins/forc-index/src/ops/forc_index_new.rs
  plugins/forc-index/src/utils/defaults.rs
  plugins/forc-index/src/utils/mod.rs
Labels: enhancement, plugin

#558 enhancement: forc postgres
  .gitignore
  Cargo.lock
  Cargo.toml
  config.yaml
  docs/README.md
  packages/fuel-indexer-api-server/src/commands/mod.rs
  packages/fuel-indexer-lib/src/defaults.rs
  packages/fuel-indexer-lib/src/utils.rs
  packages/fuel-indexer-plugin/src/lib.rs
  packages/fuel-indexer-plugin/src/native.rs
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/assets/simple_wasm.wasm
  packages/fuel-indexer-tests/scripts/e2e.bash
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer/src/commands/run.rs
  plugins/forc-index/Cargo.toml
  plugins/forc-index/README.md
  plugins/forc-index/src/cli.rs
  plugins/forc-index/src/commands/start.rs
  plugins/forc-index/src/ops/forc_index_check.rs
  plugins/forc-index/src/ops/forc_index_init.rs
  plugins/forc-index/src/ops/forc_index_start.rs
  plugins/forc-postgres/Cargo.toml
  plugins/forc-postgres/README.md
  plugins/forc-postgres/src/bin/forc-postgres.rs
  plugins/forc-postgres/src/cli.rs
  plugins/forc-postgres/src/commands/create.rs
  plugins/forc-postgres/src/commands/drop.rs
  plugins/forc-postgres/src/commands/mod.rs
  plugins/forc-postgres/src/commands/start.rs
  plugins/forc-postgres/src/commands/stop.rs
  plugins/forc-postgres/src/lib.rs
  plugins/forc-postgres/src/ops/forc_postgres_createdb.rs
  plugins/forc-postgres/src/ops/forc_postgres_dropdb.rs
  plugins/forc-postgres/src/ops/forc_postgres_startdb.rs
  plugins/forc-postgres/src/ops/forc_postgres_stopdb.rs
  plugins/forc-postgres/src/ops/mod.rs
  plugins/forc-postgres/src/pg.rs
  plugins/forc-postgres/src/utils.rs
Labels: enhancement, plugin

#587 fix: add manifest to forc-index start
  plugins/forc-index/src/ops/forc_index_start.rs
Labels: bug, plugin

#592 ci: add check-is-release-branch step
  .github/workflows/ci.yml
Labels: ci

#591 v0.3.0
  Cargo.lock
  examples/block-explorer/explorer-index/Cargo.toml
  examples/hello-world-native/hello-index-native/Cargo.toml
  examples/hello-world/hello-index/Cargo.toml
  examples/hello-world/hello-world-data/Cargo.toml
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-database/Cargo.toml
  packages/fuel-indexer-database/database-types/Cargo.toml
  packages/fuel-indexer-database/postgres/Cargo.toml
  packages/fuel-indexer-lib/Cargo.toml
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-metrics/Cargo.toml
  packages/fuel-indexer-plugin/Cargo.toml
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple-wasm/Cargo.toml
  packages/fuel-indexer-types/Cargo.toml
  packages/fuel-indexer/Cargo.toml
  plugins/forc-index/Cargo.toml
  plugins/forc-index/src/utils/defaults.rs
  plugins/forc-postgres/Cargo.toml
Labels: release

#594 fix: dont run forc-index job on master
  .github/workflows/ci.yml
Labels: bug, ci

#596 fix: update docker deps
  ci/Dockerfile.aarch64-unknown-linux-gnu-clang
  ci/Dockerfile.x86_64-unknown-linux-gnu-clang
  deployment/Dockerfile
Labels: bug, infrastructure

#597 fix: don't use patch version for str comp
  .github/workflows/ci.yml
Labels: ci

#606 fix: remove tmp ci hack
  .github/workflows/ci.yml
  examples/block-explorer/explorer-index/explorer_index.manifest.yaml
Labels: ci

#598 chore: upgrade `fuels-rs` to v0.36
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  ci/Dockerfile.fuel-node
  examples/block-explorer/explorer-index/Cargo.toml
  examples/hello-world-native/hello-index-native/Cargo.toml
  examples/hello-world/docker-compose.yaml
  examples/hello-world/hello-index/Cargo.toml
  examples/hello-world/hello-world-data/Cargo.toml
  examples/hello-world/hello-world-data/src/main.rs
  examples/hello-world/hello-world-node/Cargo.toml
  examples/hello-world/hello-world-node/src/main.rs
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-macros/src/native.rs
  packages/fuel-indexer-macros/src/wasm.rs
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-schema/src/lib.rs
  packages/fuel-indexer-schema/src/snapshots/fuel_indexer_schema__tests__fragments_some_types-19.snap
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/components/fuel-node/Cargo.toml
  packages/fuel-indexer-tests/components/fuel-node/src/main.rs
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/src/lib.rs
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple-wasm/Cargo.toml
  packages/fuel-indexer-tests/components/web-api/Cargo.toml
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/out/debug/fuel-indexer-test-abi.json
  packages/fuel-indexer-tests/contracts/fuel-indexer-test/src/main.sw
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/src/lib.rs
  packages/fuel-indexer-tests/tests/e2e/graphql_api_postgres.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/tests/integration/service.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.stderr
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.stderr
  packages/fuel-indexer-types/Cargo.toml
  packages/fuel-indexer-types/src/abi.rs
  packages/fuel-indexer-types/src/lib.rs
  packages/fuel-indexer/Cargo.toml
  packages/fuel-indexer/src/executor.rs
  plugins/forc-index/Cargo.toml
  plugins/forc-index/src/utils/defaults.rs
Labels: P: High, dependencies, blocking, sway

#607 fix: update example dir structure
  .DS_Store
  .github/workflows/ci.yml
  examples/block-explorer/docker-compose.yaml
  examples/block-explorer/explorer-index/explorer_index.manifest.yaml
  examples/block-explorer/explorer-index/schema/explorer_index.schema.graphql
  examples/hello-world-native/hello-index-native/schema/hello_index_native.schema.graphql
  examples/hello-world-native/hello_index_native.manifest.yaml
  examples/hello-world/hello-index/hello_index.manifest.yaml
  examples/hello-world/hello-index/schema/hello_index.schema.graphql
Labels: ci, chore

#608 v0.4.0
  Cargo.lock
  examples/block-explorer/explorer-index/Cargo.toml
  examples/hello-world-native/hello-index-native/Cargo.toml
  examples/hello-world/hello-index/Cargo.toml
  examples/hello-world/hello-world-data/Cargo.toml
  packages/fuel-indexer-api-server/Cargo.toml
  packages/fuel-indexer-database/Cargo.toml
  packages/fuel-indexer-database/database-types/Cargo.toml
  packages/fuel-indexer-database/postgres/Cargo.toml
  packages/fuel-indexer-lib/Cargo.toml
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-metrics/Cargo.toml
  packages/fuel-indexer-plugin/Cargo.toml
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple-wasm/Cargo.toml
  packages/fuel-indexer-types/Cargo.toml
  packages/fuel-indexer/Cargo.toml
  plugins/forc-index/Cargo.toml
  plugins/forc-index/src/utils/defaults.rs
  plugins/forc-postgres/Cargo.toml
Labels: release

#610 docs: de-emphasize docker in docs
  docs/README.md
  docs/src/SUMMARY.md
  docs/src/quickstart/index.md
Labels: documentation, book

#613 Bump to SDK version 0.37.1 prior to v0.4.0
  Cargo.lock
  examples/block-explorer/explorer-index/Cargo.toml
  examples/hello-world-native/hello-index-native/Cargo.toml
  examples/hello-world/hello-index/Cargo.toml
  examples/hello-world/hello-world-data/Cargo.toml
  packages/fuel-indexer-macros/Cargo.toml
  packages/fuel-indexer-schema/Cargo.toml
  packages/fuel-indexer-tests/Cargo.toml
  packages/fuel-indexer-tests/components/fuel-node/Cargo.toml
  packages/fuel-indexer-tests/components/indices/fuel-indexer-test/Cargo.toml
  packages/fuel-indexer-tests/components/indices/simple-wasm/simple-wasm/Cargo.toml
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/integration/service.rs
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_abi_arg_includes_invalid_type.stderr
  packages/fuel-indexer-tests/trybuild/fail_if_attribute_schema_arg_is_invalid.stderr
  packages/fuel-indexer-types/Cargo.toml
  plugins/forc-index/Cargo.toml
  plugins/forc-index/src/utils/defaults.rs
Labels: dependencies

#614 chore: remove temp CI forc-index workaround
  .github/workflows/ci.yml
Labels: ci, chore

#600 chore: ensure proper testing and analysis of packages on CI
  .github/workflows/ci.yml
  packages/fuel-indexer-macros/src/indexer.rs
  packages/fuel-indexer-plugin/Cargo.toml
  packages/fuel-indexer-tests/components/fuel-node/src/main.rs
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer-tests/tests/e2e/indexing_postgres.rs
  packages/fuel-indexer-tests/tests/integration/web_api_postgres.rs
Labels: ci, chore

#618 chore: remove `sqlx-cli` install from certain CI steps
  .github/workflows/ci.yml
Labels: ci, chore, idea

#617 chore: change `fuel-indexer`'s `fuel-core` dep feature flag from `local-node` to `fuel-core-lib`
  docs/src/for-contributors/index.md
  packages/.DS_Store
  packages/fuel-indexer-tests/.DS_Store
  packages/fuel-indexer-tests/src/fixtures.rs
  packages/fuel-indexer/Cargo.toml
  packages/fuel-indexer/src/commands/run.rs
Labels: bug, chore

#626 bug: fix wallet path
  packages/fuel-indexer-tests/src/fixtures.rs
Labels: bug, testing
